### ISSUE TITLE
Keycloak 24.0.2 - ImportAuthenticatorConfigIT::shouldCreateRealmWithFlows creates test auth config twice

### ISSUE THREAD

**Issue by jonasvoelcker** [adorsys/keycloak-config-cli#1003]
### Current Behavior

When changing the keycloak version to 24.0.2 a single test keeps failing as it creates a config twice: ImportAuthenticatorConfigIT::shouldCreateRealmWithFlows

As a consequence also the next test gets broken but the error does only occur in the creation not the update of a realm.

I did some checks but didn't find a solution for this behavior. It might also be a bug inside keycloak.

### Expected Behavior

Only a single authenticator config is created and the test runs as it did before.

### Steps To Reproduce

```markdown
1. /usr/bin/env bash ./contrib/scripts/upgrade-keycloak.sh 24.0.2
2. Run ImportAuthenticatorConfigIT
```

### Environment

- Keycloak Version: 24.0.2
- keycloak-config-cli Version: next
- Java Version: 21

**Comment by Motouom** [comment]
Hello @jonasvoelcker 

Thanks for reporting the issue.

We have tried this several times and everything works just fine. Please i would like you to double check and see if the test error does no come from your side. Please give a feedback so that we can know if it is okay to you too
