### ISSUE TITLE
authenticatorConfig is ignored

### ISSUE THREAD

**Issue by MBA-aix** [adorsys/keycloak-config-cli#1084]
### Current Behavior

I manually configured keycloak, including the setting in this screen

![Screenshot from 2024-07-01 11-30-37](https://github.com/adorsys/keycloak-config-cli/assets/59694901/55733fcb-bc20-4dc0-8b3c-cdec885f71ee)

which is important for my stuff to work. Then I exported the config via `kc.sh export` and got the config file in JSON format. This file contains the following section, where I assume the above screen is stored 
```json
  "authenticatorConfig": [
    {
      "alias": "keycloak-us-oidc",
      "config": {
        "defaultProvider": "keycloak-us-oidc"
      },
      "id": "d863d33c-de7a-4649-a005-54d6b424f664"
    }
  ],
```
but when this configuration is applied during the next deployment, somehow that configuration seems to be missing.

[
![Screenshot from 2024-07-01 11-30-56](https://github.com/adorsys/keycloak-config-cli/assets/59694901/c67fdbc6-1218-4c6a-a401-405a91d09fd0)
](url)

### Expected Behavior

I expect the exported `authenticatorConfig` configuration applied again to lead to the exact same resulting configuration (in the UI) again. 

### Environment

- Keycloak Version: `docker.io/bitnami/keycloak:24.0.4-debian-12-r1`
- keycloak-config-cli Version: `docker.io/bitnami/keycloak-config-cli:5.12.0-debian-12-r5`
- Java Version: `OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)` (as of the config-cli image)

**Comment by jonasvoelcker** [comment]
Hi @MBA-aix,

the tool works without IDs, you just have to put the alias (keycloak-us-oidc) into the field authenticatorFlow.

Please let us know if that worked.

Best Regards
Jonas

**Comment by MBA-aix** [comment]
Hi @jonasvoelcker,

first and foremost, that did the trick! I removed the `id` fields and everything works as expected.

Just one more question: Is your statement about IDs universal, i.e. there should not be any such `"id": "<uuid>"` properties in the config export or is this only true for the `authenticatorConfig` part?

Thanks in advance!

**Comment by jonasvoelcker** [comment]
Hey @MBA-aix,

whereever references are used (e.g. authFlowOverrides) it uses the names instead of the IDs as they are generated by Keycloak and they are not equal through the different stages.

You can easily delete every id-row in your export, you just need to reference without the IDs though.

**Comment by francis-pouatcha** [comment]
Documentation will be added to the project!
