### ISSUE TITLE
NPE when using custom policy in AuthorizationPolicy

### ISSUE THREAD

**Issue by bohmber** [adorsys/keycloak-config-cli#1095]
### Current Behavior

When importing client with custom policy the import stops with a NPE

`
java.lang.NullPointerException: RESTEASY004645: templateValues entry was null
org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.resolveTemplates(ClientWebTarget.java:170)
org.jboss.resteasy.client.jaxrs.internal.ClientWebTarget.resolveTemplates(ClientWebTarget.java:26)
org.jboss.resteasy.client.jaxrs.internal.proxy.SubResourceInvoker.invoke(SubResourceInvoker.java:59)
org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:102)
jdk.proxy2/jdk.proxy2.$Proxy104.policy(Unknown Source)
de.adorsys.keycloak.config.repository.ClientRepository.updateAuthorizationPolicy(ClientRepository.java:246)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.updateAuthorizationPolicy(ClientAuthorizationImportService.java:489)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.createOrUpdateAuthorizationPolicy(ClientAuthorizationImportService.java:467)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.createOrUpdateAuthorizationPolicies(ClientAuthorizationImportService.java:447)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.updateAuthorization(ClientAuthorizationImportService.java:174)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.updateClientAuthorizationSettings(ClientAuthorizationImportService.java:121)
de.adorsys.keycloak.config.service.ClientAuthorizationImportService.doImport(ClientAuthorizationImportService.java:98)
`

### Expected Behavior

Import without error.

### Steps To Reproduce

```markdown
There are no custom policies available in the keycloak-config-cli project hard to reproduce.
```

### Environment

- Keycloak Version: 25.0.1
- keycloak-config-cli Version: v6.1.5
- Java Version: 21

**Comment by minanis** [comment]
I have same issue,
but one point to add, if I tried to update the autherization settings of existing customer I got same error.
But if I tried to remove the client and import everything again (client with autherization settings) it works well.


I appritiate if there is a fix or even workaround soon
