### ISSUE TITLE
Config update is very slow when there are 1000s of clients

### ISSUE THREAD

**Issue by erwin1** [adorsys/keycloak-config-cli#1104]
### Problem Statement

Use-case:
- keycloak-config-cli is used to update general realm configuration, custom authentication flows, ...
- but it's **not** used to manage clients

Running keycloak-config-cli against a Keycloak instance with 1000s of clients is very slow (5+ minutes) because a partialExport including clients is run at the start.

https://github.com/adorsys/keycloak-config-cli/blob/main/src/main/java/de/adorsys/keycloak/config/service/ScopeMappingImportService.java#L68

### Proposed Solution

Not sure if this would break other things, but for this use-case it would make sense to be able to exclude clients so they don't need to get exported.

Or maybe there are other work-arounds that could be used here?

### Environment

- Keycloak Version: 24.0.1
- keycloak-config-cli Version: 5.11.1
- Java Version: 17

**Comment by AssahBismarkabah** [comment]
Hi @erwin1, 

I've observed the same latency issue in updating the config across multiple clients—it’s indeed slow. While excluding certain clients is an option, it risks potential issues like incomplete or incorrect scope mappings, improperly set default client scopes, and missing protocol mappers for specific clients.

I explored a selective export approach, but it’s not feasible at scale. Manually specifying thousands of client IDs in the config is both tedious and unscalable, especially in large environments.

It seems we’ll need to explore more efficient methods to handle this issue effectively probably  Allowing users to specify patterns for excluding or including clients, rather than listing individual client IDs..

**Comment by erwin1** [comment]
Quick update: the work-around in our case was simply to make sure nothing client related existed in the new config file(s). In that case keycloak-config-cli automatically excludes the full client export, which is nice.

I think the real solution is to improve the client export at the Keycloak side.

**Comment by AssahBismarkabah** [comment]
> Quick update: the work-around in our case was simply to make sure nothing client related existed in the new config file(s). In that case keycloak-config-cli automatically excludes the full client export, which is nice.
> 
> I think the real solution is to improve the client export at the Keycloak side.

It seems appropriate to close this issue while we await enhancements from  Keycloak, @erwin1?

**Comment by AssahBismarkabah** [comment]
Hi @michaljelonek 
While we don't currently have a built-in feature to specify which clients to export, there are a few potential workarounds you could consider,  
As mentioned earlier, if you ensure your configuration files don't include any client-related settings which doesn't have any changes you want to make, kccli will automatically exclude the full client export. This could significantly speed up the process for your 40-50 managed clients.
ou could potentially develop a custom script that interacts directly with Keycloak's REST API to manage your specific set of clients, bypassing the need for a full export.

Regarding a Keycloak issue to track, I couldn't find a specific one for this performance problem. It might be worth creating a new issue in  Keycloak  to highlight this performance concern with large numbers of clients.
We'll keep this feedback in mind for future improvements to keycloak-config-cli. In the meantime, if you find a solution that works well for your use case, please feel free to share it here as it could benefit others facing similar challenges.

**Comment by michaljelonek** [comment]
Thanks @AssahBismarkabah, unfortunately using REST API directly is what we want to move _away_ from. We already have a "migrator" tool that talks with Keycloak directly and applies necessary changes, including the clients. It's something we simply do not want to maintain anymore. It's also stateless, and prone to errors when something is modified via the UI.

The whole reason we want to use this is to manage clients, frankly that's mostly what we care about. 

I've filed the following issue in Keycloak - https://github.com/keycloak/keycloak/issues/35233.

**Comment by Luegg** [comment]
Hi @AssahBismarkabah, we're also running into this issue with our use case: We have a couple of dozens kccli-managed clients and thousands of self-registered ones. Currently, we're lucky enough that we only run into the issue when the caches are not yet warmed up but this significantly adds to the overall deployment time and a hard limit is just around the corner.

A possible solution for us could be an option in kccli that allows to specify a client attribute to select clients managed by kccli (clients can be filtered accordingly as described in https://github.com/keycloak/keycloak/issues/25976). Would that be aligned with the proposed solution?
