### ISSUE TITLE
No stdout output/feedback during long series of authenticator config update requests

### ISSUE THREAD

**Issue by gim-** [adorsys/keycloak-config-cli#1108]
### Problem Statement

When applying a config with custom authentication flow, somewhere near the end **keycloak-config-cli** makes a series of silent requests to update authenticator configurations, even if they haven't changed. This can be seen in the Keycloak admin events:
```
{"authUsername":"admin","realmName":"REALM","resourcePath":"authentication/config/3b7931a9-0b0b-4419-b53a-b6bc8a73dc90","ipAddress":"172.18.0.1","operationType":"UPDATE","eventType":"ADMIN","resourceType":"AUTHENTICATOR_CONFIG"}
```

~~I assume due to Keycloak Admin API limitations there's no efficient way to check if config changed or not, so the tool is just overwriting everything just in case (correct me if I'm wrong).~~ (since the tool is using realm export representation, can't it compare new config with old one to avoid redundant updates?)

But I'd expect some feedback when it does it instead of silence, as the delay is quite significant with a large number of configurations in a file.

### Proposed Solution

Add some feedback to stdout when updating authenticator configs so it doesn't appear like the tool isn't doing anything.

Printing a separate log message for each request would probably be too much, so maybe it could print some progress every N number of seconds? E.g.
```
Updating authenticator configurations (0/300)
Updating authenticator configurations (50/300)
Updating authenticator configurations (110/300)
...
Updating authenticator configurations (300/300)
```

### Environment

- Keycloak Version: 22.0.11.redhat-00001
- keycloak-config-cli Version: v6.1.5
- Java Version: 21

### Acceptance Criteria

- [ ] As a user, I can see that **keycloak-config-cli** is performing a long series of UPDATE requests to Keycloak

**Comment by Motouom** [comment]
Hello @gim-

Thanks for reporting your issue. 

This Tool in general does not override directly. It does an export and compares it with your import using remote state management. You can refer to [this documentation](https://github.com/adorsys/keycloak-config-cli/blob/main/docs/MANAGED.md) to see

[This is the file that](https://github.com/adorsys/keycloak-config-cli/blob/main/src/main/java/de/adorsys/keycloak/config/service/state/StateService.java) performs the export and then does the comparison to ensure that the configurations are synchronized

**Comment by Motouom** [comment]
> Hello [@gim-](https://github.com/gim-)
> 
> Thanks for reporting your issue.
> 
> This Tool in general does not override directly. It does an export and compares it with your import using remote state management. You can refer to [this documentation](https://github.com/adorsys/keycloak-config-cli/blob/main/docs/MANAGED.md) to see
> 
> [This is the file that](https://github.com/adorsys/keycloak-config-cli/blob/main/src/main/java/de/adorsys/keycloak/config/service/state/StateService.java) performs the export and then does the comparison to ensure that the configurations are synchronized

Concerning the feedback to stdout, we will see how to work on it.
