### ISSUE TITLE
Support Partial Imports into Keycloak

### ISSUE THREAD

**Issue by joao-rebelo** [adorsys/keycloak-config-cli#1161]
### Problem Statement

In our current workflow we provide an initial configuration state, and along the time we need to release "patches" that change only some aspects of the configuration. Since keycloak configuration might have been locally changed by some other form we would like to only affect exactly what we provide as patch.

### Proposed Solution

As a simple example importing a file as

{
    "id": "xpto",
    "ssoSessionMaxLifespan": 3600
}

would change the Session Max Lifespan of the realm and leave everything else untouched

### Additional information

At the recent KeyConf it was mentioned that partial imports were already supported, but I don't see it documented and also didn't saw such an option while seeing the ImportConfigProperties class. 
if there is some other way to achieve this, then this ticket can be considered duplicated.

**Comment by Motouom** [comment]
Hello @joao-rebelo.

You are right it has been solved but no documentation has been made yet.

You should check one of the latest versions of KC-CLI [This version](https://hub.docker.com/layers/adorsys/keycloak-config-cli/6.1.6-25.0.1/images/sha256-6eec4bed616761c6273547b27628c1d0781bce9d1b55a33c1fa7f6f5ef5ee04e?context=explore)  and maybe [This version](https://hub.docker.com/layers/keycloak/keycloak/25.0.1/images/sha256-a0c0dedfee3b1b4fae57a0b0c6f215616012eb99f12201c43a8f0444f95c205d?context=explore) of keycloak.

this is an example 
```json
{
  "realm": "example-realm",
  "ssoSessionMaxLifespan": 3600,
  "users": [
    {
      "username": "testuser",
      "enabled": true,
      "email": "testuser@example.com",
      "firstName": "Test",
      "lastName": "User",
      "credentials": [
        {
          "type": "password",
          "value": "samplePassword",
          "temporary": false
        }
      ],
      "attributes": {
       
      }
    }
  ],
  "clients": [
    {
      "clientId": "your-client",
      "enabled": true,
      "redirectUris": [
        "https://app1.example.com/callb",
        "https://app2.example.com/callback",
        "https://app3.example.co/allback"
      ],
      "webOrigins": [
        "https://app1.example.c",
        "https://app2.emple.com",
        "https://app3.exale.com"
      ],
      "attributes": {
        "post.logout.redirect.uris": "https://app1.example.com/logo##https://app2.example.com/logout##https://app3.example.com/lo"
      },
      "protocol": "openid-connect",
      "publicClient": false,
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": false,
      "authorizationServicesEnabled": false,
      "fullScopeAllowed": true
    }
  ]
}
```

![Image](https://github.com/user-attachments/assets/56c28d2a-3890-4cd5-b197-0b98872355a2)
![Image](https://github.com/user-attachments/assets/27eec768-7ee9-42c4-96c6-7741108f9121)


Now, partially importing only waht i want

```json
{
  "realm": "example-realm",
  "ssoSessionMaxLifespan": 7200,

  "clients": [
    {
      "clientId": "your-client",
      "enabled": true,
      "redirectUris": [
        "https://app1.example.com/callback",
        "https://app2.example.com/callback",
        "https://app3.example.com/callback"
      ],
      "webOrigins": [
        "https://app1.example.com",
        "https://app2.example.com",
        "https://app3.example.com"
      ],
      "attributes": {
        "post.logout.redirect.uris": "https://app1.example.com/logo##https://app2.example.com/logout##https://app3.example.com/lo"
      },
      "protocol": "openid-connect",
      "publicClient": false,
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": false,
      "authorizationServicesEnabled": false,
      "fullScopeAllowed": true
    }
  ]
}
```
![Image](https://github.com/user-attachments/assets/5758333d-9c4f-4069-8751-19f48f1936a5)

![Image](https://github.com/user-attachments/assets/44e900cf-d8f9-49de-8721-1dbf971e4545)


Lastly, i import only what i want to change again. the `ssoSessionMaxLifespan` to `4hrs` and every other thing remains unchanged.
```json
{
  "realm": "example-realm",
  "ssoSessionMaxLifespan": 14400,
}
```

![Image](https://github.com/user-attachments/assets/8b9bada6-04ba-49c6-a868-3eca75480740)

![Image](https://github.com/user-attachments/assets/ec0065b3-a67b-4e36-91ca-b489409bbb89)
