### ISSUE TITLE
I can't import multiple realms

### ISSUE THREAD

**Issue by nlangh** [adorsys/keycloak-config-cli#143]
I am trying to build an automation for Keycloak in my development environment, but I keep failing to import multiple realms at once. 

``` bash
docker exec -it kc /opt/jboss/keycloak/bin/standalone.sh \
  -Djboss.socket.binding.port-offset=100 \
  -Dkeycloak.migration.action=export \
  -Dkeycloak.migration.provider=single file \
  -Dkeycloak.migration.file=/opt/tmp/realms.json
```

The above command always returns an array json.

``` 
[{"id": "Realm1", ...},
{"id": "Realm2", ...},
{"id": "Master", ...}]
``` 

However, this cannot be imported directly into Keycloak via a volume: 

`FATAL [org.keycloak.services] (ServerService Thread Pool -- 67) java.lang.RuntimeException: Failed to parse json`

The documentations and discussions on the web didn't really help me, especially since the export that Keycloak created seems to be broken. If I only have one realm (eg. Realm1) config in the json, everything runs fine, but it's hard to automate it like this.

While searching for a solution I came across this project and hoped that it works. But again I get an error when I try to import all realms at once: 

`com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of 'de.adorsys.keycloak.config.model.RealmImport' out of START_ARRAY token at [Source: (File); line: 1, column: 1]`

Somebody help me and tell me what I'm doing wrong.

**Comment by jkroepke** [comment]
Hi!

it's not supported (yet). But you can export all realms into a directory (a file each realm) then import the the whole directory once.

```
docker exec -it kc /opt/jboss/keycloak/bin/standalone.sh \
  -Djboss.socket.binding.port-offset=100 \
  -Dkeycloak.migration.action=export \
  -Dkeycloak.migration.provider=dir \
  -Dkeycloak.migration.dir=/opt/tmp/
```

```
java -jar ./target/keycloak-config-cli.jar \
    --keycloak.url=http://localhost:8080 \
    --keycloak.ssl-verify=true \
    --keycloak.user=admin \
    --keycloak.password=admin123 \
    --import.path=/opt/tmp/
```

> especially since the export that Keycloak created seems to be broken.
We had a lot of problem with realm import. Thats a reason why we wrote this utility. 

> but it's hard to automate it like this.

Can you explain the problem?

**Comment by nlangh** [comment]
> it's not supported (yet). But you can export all realms into a directory (a file each realm) then import the the whole directory once.

Thank you, this information was the missing piece I needed. My pipeline works 👍.

**Comment by jkroepke** [comment]
Looks like it wasn't documented. I extend the documentation it should be more clear now.
