### ISSUE TITLE
Support for external RealmRepresentation

### ISSUE THREAD

**Issue by SadCodePoet** [adorsys/keycloak-config-cli#163]
**Is your feature request related to a problem? Please describe.**
In some bigger projects Keycloak is customized using extensions. This produces a RealmRepresentation that is inconsistent with the "Vanilla code" ingested by keycloak-config-cli, which in turn produces import errors.

**Describe the solution you'd like**
It would greatly help to be able to ingest the RealmRepresentation from a jar file during start up, thereby enabling all custom elements in the RealmRepresentation. It would be great to specify an external JAR (the server side keycloak-admin-client.jar) as a project parameter, which maven would then pick up und the contents of that JAR would be used as source for the data model instead of the Vanilla ones.

**Describe alternatives you've considered**
The provided CustomImportService performs a similar task, however, all imports would have to be hard coded, making it a not so nice solution imho.

**Comment by jkroepke** [comment]
Do you have a link to a documentation how it's worked or how it's defined in keycloak-admin-client.jar?

**Comment by jkroepke** [comment]
@SadCodePoet could you take a lot at https://github.com/adorsys/keycloak-config-cli/pull/164 ?

**Comment by SadCodePoet** [comment]
Awesome work, thank your very much for looking into this!
