### ISSUE TITLE
Updating of ClientScope doen't include creating new ProtocolMappers

### ISSUE THREAD

**Issue by ArtemZip** [adorsys/keycloak-config-cli#183]
**Describe the bug**
I need to update std "profile" client scope with new protocol mapper. According to supported features this thing should work.

**To Reproduce**
Trying on keycloak 8 with latest version of your cli.
After importing empty realm, kc creates default clientScopes, one of them is profile. Then I import realm with next clientScopes
```
"clientScopes": [
        {
            "name": "profile",
            "protocolMappers": [
                {
                    "id": "tmp",
                    "name": "tmp",
                    "protocol": "openid-connect",
                    "protocolMapper": "oidc-usermodel-attribute-mapper",
                    "config": {
                        "user.attribute": "name",
                        "claim.name":  "tmp",
                        "access.token.claim":  "true",
                        "id.token.claim": "true",
                        "userinfo.token.claim": "true",
                        "jsonType.label":"String"
                    }
                }
            ]
        }
    ], 
```
also, if i will add id of clientScope it will ignore that.
Also I tried to create new clientScope with same configs as default profile and got 409 from server.

**Expected behavior**
It should insert/update protocol mapper into clientScope.

**Environment (please complete the following information):**
 - Keycloak Version: 8
 - keycloak-config-cli Version: latest
 - Java Version: 11

**Comment by jkroepke** [comment]
For any reason, we do not touch default clientScopes.

https://github.com/adorsys/keycloak-config-cli/blob/66675dd19a207de866cbac685161b4aae4d34b37/src/main/java/de/adorsys/keycloak/config/service/ClientScopeImportService.java#L103-L105

I can't remember why.

> Also I tried to create new clientScope with same configs as default profile and got 409 from server.

Normally, keylcloak should throw some log line at server side.

**Comment by jkroepke** [comment]
Hi!

thanks for discover some bugs. I found 3 in total related to clientScopes.

See #184 and #186 for more informations.
