### ISSUE TITLE
Cannot Create Realm Unrecognized field"clientOfflineSessionIdleTimeout"

### ISSUE THREAD

**Issue by cbett** [adorsys/keycloak-config-cli#189]
Upgraded to latest 2.3.0 release (from 1.4.0) and the keycloak import now fails with the message..
`Cannot create realm 'xxxxxxxxxxt': Unrecognized field "clientOfflineSessionIdleTimeout" (class org.keycloak.representations.idm.RealmRepresentation), not marked as ignorable`
This is against Keycloak 10.0.2.
Am I doing something wrong?

**Comment by cbett** [comment]
Just for info, when I build from the 2.0.2 Tag it works fine.
It seems 2.1.0 release (the introduction of Keycloak 11 support) breaks it for me.
OR am I packaging it wrong?

**Comment by ArtemZip** [comment]
I think you should use jar prepared for your keycloak version https://github.com/adorsys/keycloak-config-cli/releases/download/v2.3.0/keycloak-config-cli-10.0.2.jar , but maybe I am mistaking (I'm not maintainer )

**Comment by cbett** [comment]
Yes Artem you are right :-) 
I was used to building from the sources in the past which is why I missed the prepared jar files.

**Comment by jkroepke** [comment]
@cbett 

You could define the Keycloak version at build time.

```
mvn clean package -Dkeycloak.version=10.0.2
```
