### ISSUE TITLE
Fails on 4.6.0.Final of Keycloak due to unknown properties and Jackson not ignoring them

### ISSUE THREAD

**Issue by maccamlc86400** [adorsys/keycloak-config-cli#2]
Found this image, as a great and simple way to set up a test environment with keycloak.

I tried the latest version (at the time) of Keycloak and received errors, but 4.4.0.Final worked.

Just wondering if any plans to try and handle these issues with future versions?

I thought about making a fork and attempting to make work myself, but I saw in an existing PR that it has been rewritten recently.

So opening this Issue first, to hopefully find the current state :)

**Comment by borisskert** [comment]
Hi. I'm glad to hear you using our image. Thanks for your feedback.

Yes, we are planning to use this image on newer keycloak images. I just completed a lot of integration tests to make sure our import is working correctly.

I will perform a release next week, cause we need our import working for keycloak 4.4.0. After this, i will bump the keycloak dependencies to the current latest version (4.8.x).

The future plan is to keep this project up to date with the keycloak versions.

**Comment by borisskert** [comment]
Update: I have released my stuff for keycloak 4.4.0.Final and tested the same code for 4.6.0.Final and 4.8.0.Final. The only think I had to change is the keycloak dependencies in my poms. I think we could soon release the keycloak-tools for both versions.

**Comment by maccamlc86400** [comment]
Oh, that's great. Thank you.

I'm trying out v0.4.0 now with keycloak 4.4.0.Final.

Thanks for the images. Definitely makes it simpler to set up a consistent test environment :)

**Comment by borisskert** [comment]
Another update:
The fact that our code is compatible to all keycloak versions between 4.4.0.Final and 4.8.1.Final allows us to build multiple docker image per build for each keycloak version.
I changed our travis pipline to build them in a matrix and released the version **v0.4.0-1**.

For example, if you want to configure keycloak 4.6.0.Final you can pull the image **adorsys/keycloak-config-cli:v0.4.0-1-4.6.0.Final**.

We will try to support old versions as long as our code allows it to do.

**Comment by maccamlc86400** [comment]
Thanks. Looks great.

Yes, please close :)
