### ISSUE TITLE
Discussion: awesome project - is it possible to see which objects are managed by `import.state`?

### ISSUE THREAD

**Issue by sboardwell** [adorsys/keycloak-config-cli#201]
Hi there,

first off, brilliant project, kudos to all.

I was wondering if there was a way to identify which components are managed when using `import.state`. I noticed, for example, that roles are not affected, but clients are. Is there any reason not to manage roles?

I think it is a great project and would be happy to contribute if I can. Let me know.

Cheers,
Steve

**Comment by jkroepke** [comment]
Hi,

thanks for the kudos. 

About import.state, please take a look here: 

https://github.com/adorsys/keycloak-config-cli/blob/master/docs/MANAGED.md

Currently state is implemented for resources that can be purged by keycloak-config-cli.

There is no reason to not handle roles like clients. It just like not implemented and no one ask for it. 😄

If you have an idea to improve the docs, e.g wording please let me know. I'm not the best in writing documentation.

**Comment by sboardwell** [comment]
Great stuff,and thanks the for quick response. Ah, didn't see the `MANAGED.md`. Might be worth adding a link in the main `README.md` for those reading about the `import.state`.

I can have a look at the docs as soon as I have time.
