### ISSUE TITLE
Allow full override of keycloak_url i.e KEYCLOAK_FRONTEND_URL

### ISSUE THREAD

**Issue by leppaott** [adorsys/keycloak-config-cli#216]
You assume Keycloak is always listening at /auth endpoint i.e. keycloak.url + /auth.

Please let the user override this "/auth".

> Frontend request do not have to have the same context-path as the Keycloak server. This means you can expose Keycloak on for example https://auth.example.org or https://example.org/keycloak while internally its URL could be https://10.0.0.10:8080/auth.

I have needed to set my own standalone-ha.xml with web-context auth changed.

**Comment by jkroepke** [comment]
I saw this 2 weeks ago, that keycloak-config-cli always append `/auth` to the url. 

Instead make `/auth` configurable, I would like to remove this compltly but strictly is a breaking change.

No idea to solve this yet. A new property is a little to much.
