### ISSUE TITLE
Add option to remove client

### ISSUE THREAD

**Issue by ArtemZip** [adorsys/keycloak-config-cli#217]
Hi, 

We have an idea to add feature for removing clients, as we do it quite often manually. 
So, we will be happy if it become possible with that cli.

**Comment by ArtemZip** [comment]
I will try to create pull request for that issue

**Comment by jkroepke** [comment]
If you are going for a PR, please implement as "Full Managed".

See: https://github.com/adorsys/keycloak-config-cli/blob/master/docs/MANAGED.md

**Comment by ArtemZip** [comment]
Hi @jkroepke, 

Can I ask you why there are many attributes which has 256 chars, when in schema they should be 255 ? 
And if you have any suggestion, why this error appears me (also in clean master) ? 

Thanks a lot,
Artem

**Comment by jkroepke** [comment]
Could u please explain which error do you mean?
