### ISSUE TITLE
Import of realm with client scopes referencing clients let's keycloak fail with Exception

### ISSUE THREAD

**Issue by SadCodePoet** [adorsys/keycloak-config-cli#222]
**Describe the bug**
When importing a realm with client scopes referencing clients KeyCloak goes throws an exception:
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-48) Uncaught server error: java.lang.RuntimeException: Unknown client specification in scope mappings: _redacted-client_ This can be circumvented by adding _clientScopeMappings_ to the _ignoredPropertiesForRealmImport_ array.

**To Reproduce**
Unfortunately I cannot share the keycloak config for reproduction, but I will try to produce a simple repro scenario.

**Expected behavior**
No exception in Keycloak visible.

**Environment (please complete the following information):**
 - Keycloak Version: 9.0.0
 - keycloak-config-cli Version: 2.4.0
 - Java Version: 8

**Additional context**

**Comment by jkroepke** [comment]
Funny. I got this issue yesterday from internal, too.

I'm able to reproduce this issue and I could put `clientScopeMappings` to `ignoredPropertiesForRealmImport`. Then the error is gone, but the setting is not applied.

`clientScopeMappings` is only used on the Create Realm Call. It's not possible to update `clientScopeMappings`, since the property is ignore on the Update Realm call by Keycloak itself.

**Comment by jkroepke** [comment]
I found the logic how Keycloak resolves the `clientScopeMappings` on a realm import.

https://github.com/keycloak/keycloak/blob/d266165f63013f0ea3480ddaa83108ff34da407e/server-spi-private/src/main/java/org/keycloak/models/utils/RepresentationToModel.java#L1701-L1713

I created a PR which add support for `clientScopeMappings`.

**Comment by jkroepke** [comment]
@SadCodePoet Could you test the PR?

**Comment by SadCodePoet** [comment]
I will try, the problem is we are working on a Keycloak v9 based solution, migration to v11 is under way though

**Comment by jkroepke** [comment]
@SadCodePoet no problem. the fix is also available for v9.

https://github.com/adorsys/keycloak-config-cli/actions/runs/307272023
