### ISSUE TITLE
Helm chart configs referencing "file" keyword fail

### ISSUE THREAD

**Issue by agelwarg** [adorsys/keycloak-config-cli#224]
When providing configuration via `.Values.config` where a realm is configured via the `file` keyword (as opposed to `inline`), the chart fails to render.

To reproduce, specify a value for `config` with the `file` keyword as follows, and then attempt to `helm install | template ...` the chart:

```
config:
  myrealm:
    file: path/to/myrealm.json
```

This will produce an error similar to the following:
```
 executing "templates/realms.yaml" at <.Files.Get>: nil pointer evaluating interface {}.Get
```

This is likely due to `.Files.Get` not being in context while within `{{- range $name, $config := .Values.config }}`, and simply needs to be changed to `$.Files.Get`.

**Comment by jkroepke** [comment]
Makes sense! I didn't test a realm import via file yet.

Thanks for the hint.
