### ISSUE TITLE
support for referring to subgroups or group paths when creating users with json

### ISSUE THREAD

**Issue by erkkikeranen** [adorsys/keycloak-config-cli#257]
**Is your feature request related to a problem? Please describe.**

I have a group configuration which `keycloak-config-cli` can update to keycloak:

```
"groups": [
    {
      "name": "app",
      "path": "/app",
      "attributes": {},
      "realmRoles": [],
      "clientRoles": {},
      "subGroups": [
        {
          "name": "admin",
          "path": "/app/admin",
          "attributes": {},
          "realmRoles": [
            "app_admin"
          ],
          "clientRoles": {},
          "subGroups": []
        },
        {
          "name": "viewer",
          "path": "/app/viewer",
          "attributes": {},
          "realmRoles": [],
          "clientRoles": {},
          "subGroups": []
        }
      ]
    }
  ]
```

In my user.json I  try to write such user that uses one of the groups:
```
      "groups": [
        "/app/admin"
      ]
```

I can't refer to the subgroups or group hierarchy, I get an
`Could not find group '/app/admin' in realm 'app-realm'!`, so I can only refer to root level group names

**Describe the solution you'd like**

I would like to refer to my groups using paths, i.e. /app/admin/...

**Describe alternatives you've considered**

No idea

**Comment by jkroepke** [comment]
Does this work, if you import this in keycloak directly?
