### ISSUE TITLE
Create/Update WebAuthn Settings does not set Property 'User Verification Requirement'

### ISSUE THREAD

**Issue by spahrson** [adorsys/keycloak-config-cli#273]
**Describe the bug**
Creating or Updating the WebAuthn Settings does not set the property  'User Verification Requirement' (it remains empty).

**To Reproduce**
Setting the propertry for a realm e.g. `"webAuthnPolicyPasswordlessUserVerificationRequirement": "required",` has no effect.

**Expected behavior**
Should set the property.

**Environment (please complete the following information):**
 - Keycloak Version: ~10.0.3~ 11.0.3
 - keycloak-config-cli Version: 2.6.1
 - Java Version: 11

**Additional context**

**Comment by jkroepke** [comment]
> Keycloak Version: 10.0.3

i assume 11.0.3. 10.0.3 does not exists.

I test this:

```json
{
  "enabled": true,
  "realm": "simple",
  "webAuthnPolicyPasswordlessUserVerificationRequirement": "required"
}
```

I could verify the setting is set on realm creation and realm update. Tested both 10.0.2 and 11.0.3

**Comment by spahrson** [comment]
Hmm, I tested it again and it doesn't update the value. I'll try to figure out the problem with a reduced realm import. I keep you updated.

**Comment by spahrson** [comment]
When you create a new area, the property appears to be set correctly. If you manually changed the value to any other value (including blank / unspecified) in the web console, it will not update correctly because the checksum will remain the same. Can you confirm this behavior?

**Comment by jkroepke** [comment]
> If you manually changed the value

In this case, you have to run the import with `--import.force` which just disables the checksum check.
