### ISSUE TITLE
Support for authorization using client_credentials flow

### ISSUE THREAD

**Issue by laszlomiklosik** [adorsys/keycloak-config-cli#302]
_keycloak-config-cli_ can currently be used with end-user credentials (username and password) but this option is not optimal for our use case (also not an ideal approach for server to server authorization).

Although we forbid access from the public internet to the admin console and admin REST API of all realms, we consider that this right it's still too powerful for an end-user and would preferably use the OAuth client_id and client_secret (with grant_type=client_credentials) to obtain the OAuth tokens. Our current workaround is to create a temporary user and delete it after _keycloak-config-cli_ finished running.

The "direct grant" (the Keycloak terminology for Resource Owner Password Credentials Grant or grant_type=password) is not considered future-proof & secure by the OAuth Current Best Practice (see https://tools.ietf.org/html/draft-ietf-oauth-security-topics-16#page-8) and there are some chances that it gets deprecated & removed in new versions of Keycloak.

We would be happy to contribute with a related PR. Would you be interested in a related contribution?

Thanks and congrats for the very useful tool and its test-driven implementation!

**Comment by jkroepke** [comment]
> We would be happy to contribute with a related PR. Would you be interested in a related contribution?

Sure if its possible with the existing keycloak admin-client. 

But i guess it is:
https://github.com/keycloak/keycloak/blob/35ecaf07cb07fba0d9ebcea20cb0e5c76c13b0a4/integration/admin-client/src/main/java/org/keycloak/admin/client/KeycloakBuilder.java#L42-L51

Looks like, it just like more property and conditions and a test case, right?

**Comment by laszlomiklosik** [comment]
Thanks for the quick answer!

Happy to see that the ground is already prepared in the code.
It will require a new confidential OAuth client configured with the client_credentials flow and a linked service account with the corresponding realm-management client roles assigned. There is no default OAuth client configured in Keycloak like this out of the box.

Indeed it's about 2 new properties (grant_type, client_secret), conditions and a test case. 
Either me or a colleague will come back on this in the next days.

**Comment by jkroepke** [comment]
@laszlomiklosik looking at keycloak admin-client, the condition are handled by the client it self.

It looks like just adding properties and create a test case for this scenario. 

> There is no default OAuth client configured in Keycloak like this out of the box.

It will be result into, import a configured realm via username/password - then just login using the oauth client credentials flow.

**Comment by razvan-tufisi** [comment]
PR with changes added.
