### ISSUE TITLE
Add curl to docker image

### ISSUE THREAD

**Issue by todeb** [adorsys/keycloak-config-cli#303]
Could you please add curl binary to docker image?
it will help with fetching realm configurations from external service.

**Comment by jkroepke** [comment]
Does wget not fit?

**Comment by jkroepke** [comment]
If not, does it fits for your case, the keycloak-config-cli would support remote locations of realm binaries? Or do you have do some special options of curl to fetch your config?

**Comment by todeb** [comment]
At least on adorsys/keycloak-config-cli:v3.0.0-10.0.2 there is no wget also.
Probably will fit anything that allows get file from webserver with auth basic.
In that case I'd like to fetch config files from Spring Cloud Config Server, https://spring.io/projects/spring-cloud-config

**Comment by jkroepke** [comment]
Hi!

wget is now available, additionally `import.path` supports remote urls now.
