### ISSUE TITLE
keycloak-config-cli and keycloak-operator

### ISSUE THREAD

**Issue by todeb** [adorsys/keycloak-config-cli#308]
Hi,

What do you think about keycloak operator? Seems that it is also capable at importing configuration.
https://operatorhub.io/operator/keycloak-operator

Do you see any advantage of operator over config cli and vice versa on managing configurations?

**Comment by jkroepke** [comment]
HI,

as I cloud native fan, I would prefer the keycloak-operator over keycloak-config-cli. 

But weeks ago I tried to setup the keycloak-operator including the OLM stack. Unlike operator like prometheus operator, the keycloak operator looks quite complex. I was not able to start it.

> Do you see any advantage of operator

Speaking for all operators: Yes. You could use tools like helm or even kubectl apply to configure any type of application, in this example: keycloak. It might be extrem developer friends, if you company has something like a platform team which could manage such operator.

Thanks for asking this question. I will look into it how I could keycloak-config-cli wrap in an operator.

**Comment by jkroepke** [comment]
I'm going to close this issue. I tried something with the java operator sdk, but I'm not able to run config-cli with-in the operator loop.

**Comment by Bessonov** [comment]
TBH, I don't see any value which an operator can bring to the table for kcc.

Operators make total sense for workloads with a **lifecycle**. Like unattended load watching and scaling databases beside HPA. But kcc is one-shot-job¹. Using it as a kubernetes' `Job` allows composition and universal usage. It doesn't make any difference to deploy a Job, a ConfigMap or a CRD. But coupling to an operator slows down development of kcc and no body really want that.

And renaming of realm or sub-imports are unrelated to operator. See -> ¹.

¹ I'm aware that kcc is stateful and has own lifecycle, but well, it's unrelated to operator's lifecycle.

**Comment by jkroepke** [comment]
@Bessonov  I agree with you in terms of Operators. kcc do not operate a realm. the just an file to API proxy)

Going away from operations and looking to controllers or sidecars (like https://github.com/kiwigrid/k8s-sidecar), there is still a use case, the same way as grafana has implement a sidecar container to import dashboards.

But this increase complexity on code site has a greater weight than the benefits here.

> But coupling to an operator slows down development of kcc and no body really want that.
Yeah, and mention I still have no clue about software or java development. It might be go even worse.

I also agree for @xRodney, the feature to create a single client through as CRD has some benefits, for example if a create a client through CRD, the operation returns a kubernetes secrets which stores the client-id/client-secret. It avoids the manual credentials handling. 

But this is already covered by https://github.com/keycloak/keycloak-operator

**Comment by xRodney** [comment]
I still believe that there are use cases that *currently* cannot be fulfilled using neither kcc, nor the official keycloak-operator.

But I understand that this is not what kcc wants to be and the maintenance costs would be too high. After all, stalling of development of such a useful tool is the last thing I would want.

Thanks for hearing me out.
