### ISSUE TITLE
`eventsEnabled` is set to false as default

### ISSUE THREAD

**Issue by spahrson** [adorsys/keycloak-config-cli#338]
**Describe the bug**
If not explicitly configured, the CLI always sets `eventsEnabled` in realms to `false`. If you are using a split configuration (multiple files) you have to make sure that the configuation file with `"eventsEnabled": true` is applied last. But IMHO the order of the configuration files is not a supported feature actually.

**To Reproduce**
Apply first:
```
{
  "id": "test",
  "realm": "test",
  "eventsEnabled": true,
}
```
And then:
```
{
  "id": "test",
  "realm": "test"
}
```
=> Events are disabled. But should be enabled.

**Expected behavior**
`eventsEnabled` should *not* be set to false when not configured explicitly.

**Environment (please complete the following information):**
 - Keycloak Version: 12.0.3
 - keycloak-config-cli Version: 3.1.0
 - Java Version: 11

**Additional context**

**Comment by jkroepke** [comment]
It feels like a bug inside Keycloak itself?

**Comment by jkroepke** [comment]
Fixed in https://github.com/adorsys/keycloak-config-cli/commit/d8c1e68400d3e6526a90eddd0ef9771d5e5b0180
