### ISSUE TITLE
Unexpected behaviour for client scope mapping on a client scope

### ISSUE THREAD

**Issue by Oh-tech** [adorsys/keycloak-config-cli#360]
[00_create_realm_with_client_scope_mapping.json.zip](https://github.com/adorsys/keycloak-config-cli/files/6213146/00_create_realm_with_client_scope_mapping.json.zip)

Hi.

I have come across some bug(s) when I tried to maintain the state of realms in my Kycloak with the tool.

**Describe the bug**
Missed the ability to map the client roles to a client scope. Please consider the following snippet:

```json
{
  ...
  "clientScopeMappings": {
    "moped-client": [
      {
        "client": "other-moped-client",
        "roles": [
          "moped-role"
        ]
      },
      {
        "clientScope": "moped-scope",
        "roles": [
          "2nd-moped-role"
        ]
      }
    ]
  },
  ....
}

```
The `2nd-moped-role` role of the `moped-client` will not be mapped to the `moped-scope` client scope, but strangely enough to the `account` client, which is simply the first client which will be returned by the `/admin/realms/{realm}/clients` endpoint.  

And this implies the second found issue: 
The `ClientRepository.searchByClientId(String realmName, String clientId)` method returns the first client of the realm when the `clientId` parameter is `null`.

**To Reproduce**
Please try to import the attached JSON.

**Expected behavior**
1. The `2nd-moped-role` of the moped-client is assigned to the `moped-scope` client scope.
2. The `ClientRepository.searchByClientId` returns empty Optional when the `clientId` parameter is null.

**Environment (please complete the following information):**
 - Keycloak Version: [e.g. 11.0.3]
 - keycloak-config-cli Version: [e.g. 3.2.0]
 - Java Version: [11]

Thank you in advance.

**Comment by jkroepke** [comment]
Fixed in #361
