### ISSUE TITLE
scopeMappings of clients are not imported correctly, when the corresponding realm already exists

### ISSUE THREAD

**Issue by woelkjulian** [adorsys/keycloak-config-cli#40]
keycloak.version:
![keycloak_server_info](https://user-images.githubusercontent.com/25659642/63951979-02e91d80-ca7f-11e9-8643-b4f0b568396d.png)

config-cli pom:
![config-cli-pom](https://user-images.githubusercontent.com/25659642/63952044-201dec00-ca7f-11e9-89df-ef0893a21e21.png)

Hey,

I have an issue when importing scopeMapping changes to realms that are already existent.

Steps to recreate issue:

1. Run keycloak via export.single-realm-files.docker-compose.yml

2. Import the attached "moped-scope-mappings.json" with the config-cli, where I just added a new client (client-scope-test), a new role (client-scope-test) and a scopeMapping to connect both

[moped-scope-mappings.json.zip](https://github.com/adorsys/keycloak-config-cli/files/3556107/moped-scope-mappings.json.zip)

3. Check the keycloak Admin GUI for the new client and its scope mappings, the import worked nicely as expected. see attached figure 

<img width="1396" alt="scope_mapping" src="https://user-images.githubusercontent.com/25659642/63949946-6ffab400-ca7b-11e9-8115-f68f2e45ff5a.png">

4. now remove the scope mapping within the Admin GUI, see attached figure 

![removed_scope_mapping](https://user-images.githubusercontent.com/25659642/63951368-e4ceed80-ca7d-11e9-8501-86b90044e6b7.png)

5. now reimport the moped-scope-mappings.json with the config-cli

6. I would expect, that the scope mapping will be imported again and that the role is assigned correctly to the client, but it isn`t.

Note: It doesnt matter if the client already exists or not. The scope mappings only got imported correctly when the realm didnt exist. the parameter --import.force=true didnt change anything for me

**Comment by borisskert** [comment]
Fixed with version v0.8.0
