### ISSUE TITLE
Unrecognized field "oauth2DeviceCodeLifespan" against 11.0.2 with docker:latest

### ISSUE THREAD

**Issue by pmorch** [adorsys/keycloak-config-cli#430]
**Describe the bug**

When applying `contrib/example-config/moped.json` against 11.0.2, I get the same error reported in #414. But that error focuses on how something changed in keycloak 13. This issue is about 11.0.2.

**To Reproduce**

Apply `contrib/example-config/moped.json` configuration against keycloak 11.0.2 using 

```
docker run .... adorsys/keycloak-config-cli:latest
```

See issue. See that it works fine with:

```
docker run .... adorsys/keycloak-config-cli:latest-11.0.3
```

**Expected behavior**

I expect that either `adorsys/keycloak-config-cli:latest` should work, or the [Compatibility Matrix](https://github.com/adorsys/keycloak-config-cli#compatibility-matrix) should show me that is not the case.

**Environment (please complete the following information):**
 - Keycloak Version: [e.g. 11.0.2]
 - keycloak-config-cli Version: [latest]
 - Java Version: [whatever is in the docker image. 11?]

**Comment by jkroepke** [comment]
Hi @pmorch 

the docker tag `latest` reference the latest release of `keycloak-config-cli` and use the latest available version of the keycloak admin-cli.

`latest-11.0.3` is latest version of `keycloak-config-cli` but it use the `keycloak admin-cli` from 11.0.3.

> I expect that either adorsys/keycloak-config-cli:latest should work

I clarify the documentation about the docker tags, this may should help.


Rare versions of Keycloak supporting multiple versions, e.g. the `keycloak admin-cli` from Keycloak 12 may worked with Keycloak 11.

Before the release of Keycloak 13, `latest` uses the `keycloak admin-cli` from Keycloak 12 that worked for Keycloak 11, too.
