### ISSUE TITLE
Synchronization of user federation after import

### ISSUE THREAD

**Issue by JaquierM** [adorsys/keycloak-config-cli#438]
**Is your feature request related to a problem? Please describe.**
I have a Keycloak configuration with a user federation configured, when I deploy the configuration I still need to login in to sync all the user.

**Describe the solution you'd like**
When the realm contain one or more user federation, I like to have a immediate synchronization with the federation.

**Describe alternatives you've considered**
1. Call with my deployment tool the sync API.
2. Set a short automatic synchronization (10 min).
3. Add a option to this tool.

**Additional context**
Here a config for the realm using a Ldap federation and the ldap configuration.
[context.zip](https://github.com/adorsys/keycloak-config-cli/files/6606430/context.zip)

These a used into the test 'SyncUserFederationIT' created on the link PR.

**Comment by jkroepke** [comment]
Resolved by #439
