### ISSUE TITLE
Session is not cleared after config-cli run 

### ISSUE THREAD

**Issue by arulrajnet** [adorsys/keycloak-config-cli#472]
**Given** Using keycloak config cli version `v0.8.0`
**When** Run the following command in the shell
**Then** After successful execution, There are active sessions in User -> username (admin) -> Sessions which is created by config cli. 

```
java -jar ./keycloak-config-cli.jar \
  --keycloak.url=http://localhost:8080/auth \
  --keycloak.user=admin \
  --keycloak.password=admin \
  --import.file=realm.json
```

**Expected behavior**
After running the command, the config cli should logout the session which is used. There should be no session from `admin-cli` client. 

**Environment:**
 - Keycloak Version: 7.0.0
 - keycloak-config-cli Version: v0.8.0-7.0.0
 - Java Version: 1.8.0_292
 
![flameshot_2021-07-12_06-06-19](https://user-images.githubusercontent.com/834529/125215243-78a7ac80-e2d8-11eb-89bf-c182cda745cb.png)

**Comment by jkroepke** [comment]
Hi,

thanks for reporting this. Currently there is no builtin method inside the keycloak client to terminate a sessions.

See: https://github.com/keycloak/keycloak/pull/8258

**Comment by arulrajnet** [comment]
Ok. 

@jkroepke Actually, we can logout the current session using refresh token. Here is a curl example

```
# logout
curl -s -H "Authorization: bearer $access_token" \
-d "client_id=admin-cli" \
-d "refresh_token=$refresh_token" \
"http://localhost:8080/auth/realms/master/protocol/openid-connect/logout"
```

This may not be possible in keycloak-admin-client. Just for your information.

**Comment by jkroepke** [comment]
If there is a way to do a request manually (using the RESTeasy java library), I could implement it. 

Otherwise, I hope they implement the PR soo.
