### ISSUE TITLE
documentation / help for running idempodent configs - checksum question

### ISSUE THREAD

**Issue by erkkikeranen** [adorsys/keycloak-config-cli#50]
Hi, 

is there any help or documentation if I want to achieve idempodent configuration provision of the cli tool?

For example, it detects that my realms are existing and no actions are done, 
but it always says it updates my realm clients, roles and users I present in the JSONs. 

What is the checksum used for?

For example, the cli tool logs:

`2020-03-04 07:40:48.273 DEBUG 178 --- [           main] d.a.k.config.service.RealmImportService  : No need to update realm 'master', import checksum same: '324a31eb1912f70114550e958134e667391266facd618769646d799372bc3e58931d93f020d88e60aed9fd28be65490fb5800d43ae7aee6d0ff993a19b765a61'`

Question: 

Does the script names have any semantics or processing order?

Would it be possible that script names could have semantics, for example like in flyway (except that you don't store the state anywhere)

So that you could define 
* Repeatable scripts
* Policy (Create if not exists, Update, Create once)
* Processing order with number

I am using docker image adorsys/keycloak-config-cli:v0.8.0-7.0.0

**Comment by jkroepke** [comment]
Hi!

> What is the checksum used for?

The checksum is an hash of the provided json. The config-cli should compare the file hash with the hash run by the last run. If the hash is the same, the realm is not touched as you expect it.

On a quick test I it worked like you expected. I used this config: https://github.com/adorsys/keycloak-config-cli/blob/develop/example-config/moped.json .

If I re-run the config-cli twice I can't see any changes. (no create or changes seen in audit log)

> Does the script names have any semantics or processing order?

Yes. See:
https://github.com/adorsys/keycloak-config-cli/blob/667f31dcc7e6ca3370d4b66d195f287dda5fbee1/config-cli/src/main/java/de/adorsys/keycloak/config/service/RealmImportService.java#L143-L159
The order should be the same. But i'm unware of the process order of the keycloak-admin-cli used by this project. 

> Policy (Create if not exists, Update, Create once)

Yes, if its possible. In some rare condition (like flows) its required to delete and recreate the flow, since this is limited by keycloak.

Example for user:
https://github.com/adorsys/keycloak-config-cli/blob/8ec8f7be3cff44cda8c8a2dacc9baab1aa2e4170/config-cli/src/main/java/de/adorsys/keycloak/config/service/UserImportService.java#L54-L64

Create user if not exists, then update the roles based on the difference between config json and keycloak.



Can you provide a full json to reproduce this issue?

**Comment by erkkikeranen** [comment]
> The checksum is an hash of the provided json. The config-cli should compare the file hash with the hash run by the last run. If the hash is the same, the realm is not touched as you expect it.

Where is this hash state stored? I am always running the configurator in a container that is disposed after run in my deployment, from where would I expect it to get the last checksum?

I am sorry if I've misunderstood something or if I am using the tool wrong, but haven't found explicit documentation. 

My use case is following:

I am running every now and then (either on purpose, or together with keycloak deployment in docker, or the configurator container is triggered to run for example CI/CD) keycloak-config-cli as part of docker-compose or aws fargate deployment. I am not expecting changes when I run the tool. It's not a problem that it updates some of the items - anyways nothing is changed so it's idempodent in the sense.

Is keycloak-config-cli persisting something that it expects to exist on next run to function correctly?

 If keycloak-config-cli is dependant on persisted hash, I wonder if there could be stateless non-persisted hash, for example calculate a hash based on the given JSON fields comparing to the exact same fields retrieved from keycloak. 

Unfortunately i can't provide the config because of disclosure reasons. Based on my assumption I am afraid that the problem arises in my usecase, not my JSONs. 🤔

**Comment by jkroepke** [comment]
> Where is this hash state stored? I am always running the configurator in a container that is disposed after run in my deployment, from where would I expect it to get the last checksum?

This was the reason to write this utility. 

The hash is stored in a custom attribute of the realm. The information is stored inside keycloak.

> but haven't found explicit documentation.

This project hasn't a good documentation since this project is create in the free time of us. Sorry. :-)


So did you see any logs after 

> 2020-03-04 07:40:48.273 DEBUG 178 --- [ main] d.a.k.config.service.RealmImportService : No need to update realm 'master', import checksum same: '324a31eb1912f70114550e958134e667391266facd618769646d799372bc3e58931d93f020d88e60aed9fd28be65490fb5800d43ae7aee6d0ff993a19b765a61'

If not, your realm isn't touched by this tool.

**Comment by erkkikeranen** [comment]
>> Where is this hash state stored? I am always running the configurator in a container that is disposed after run in my deployment, from where would I expect it to get the last checksum?

>This was the reason to write this utility.

>The hash is stored in a custom attribute of the realm. The information is stored inside keycloak.

Okay, I found it when I looked inside keycloak db, **realm_attribute** table with a composite key per realm. 

So It seems my problem is that because I've split the configuration files to multiple JSONs, all realm checksums are updated after each file run, but finally the same checksum of last run is stored in the realm attributes. So all users, clients, realms, roles are updated each run.

Also master realm is updated on every run, even if master realm related data only exists in one JSON, but it receives the same checksum every run:
```
d.a.k.config.service.RealmImportService  : Updating realm 'master'...
d.a.k.c.service.ClientImportService      : Update client 'security-admin-console' in realm 'master'
d.a.k.config.service.RealmImportService  : Updated import checksum of realm 'master' to '6f7f3ebee3ccb0f0b29c54548250c60296b50e3bffa95efa8f93a0f50d5682747d634aaf5360ee38369daa93c638ba5549015bc9873a13e6bb48621ab624fbaf'
```

Here's the master_realm.json contents local dev env example (obfuscated)
```
{
  "id": "master",
  "realm": "master",
  "displayName": "Master",
  "enabled": true,
  "sslRequired": "none",
  "accountTheme": "keycloak",
  "adminTheme": "keycloak",
  "emailTheme": "keycloak",
  "clients": [
    {
      "clientId": "security-admin-console",
      "webOrigins": [
        "*"
      ],
      "redirectUris": [
        "http://localhost/*",
        "http://10.0.0.1/*",
      ],
      "rootUrl" : "https://something.com",
      "baseUrl" : "https://something.com"
    }
  ]
}
```

What do you think, would it be possible that **realm_attributes** could store states per file? This could give similair semantics like flyway / liquibase for doing migrations. 

Or, do you suggest that best practice is to have one migration file? I think there was a mention to keep files as small as possible.

By the way, should maybe be on other issue, but I tried to import an IDP configuration, is this supported? The Admin API supports importing of IDP configuration.

example json for IDP I'm trying to use:

```
{
  "realm": "my-realm",
  "identityProviders": [
    {
      "alias": "myidp",
      "displayName": "My IDP",
...
```

**Comment by jkroepke** [comment]
> What do you think, would it be possible that realm_attributes could store states per file? This could give similair semantics like flyway / liquibase for doing migrations.

Would something like

```
java -jar ./keycloak-config-cli.jar --keycloak.migrationKey="users"
```

help? Something like file name in combination with `import.path` would be to complex but feel free to open an own pr...

> Or, do you suggest that best practice is to have one migration file? I think there was a mention to keep files as small as possible.

In my project I use one file per realm.

> By the way, should maybe be on other issue, but I tried to import an IDP configuration, is this supported?

No restrictions from keycloak-config-cli. But the import REST API lacks sometimes. Some settings needs custom handing.

If there a problem, create a new issue please.

**Comment by jkroepke** [comment]
> Here's the master_realm.json contents local dev env example (obfuscated)

Still, it works locally using your provided config even will other json files containers other realms...

> 2020-03-09 00:05:19.227 DEBUG 31 --- [           main] d.a.k.config.service.RealmImportService  : No need to update realm 'master', import checksum same: 'a66c076f63e22399ad8c0f608ccb82ed3f0f352f074a1d05c4a13b82cb0ff5c33c92053f4bb73cdef202a2fcc3d1d14edeaacbc256eb26f20099f083923938c3'

**Comment by jkroepke** [comment]
> No restrictions from keycloak-config-cli. But the import REST API lacks sometimes. Some settings needs custom handing

Looks like there is no update mechansim.

**Comment by jkroepke** [comment]
> Looks like there is no update mechansim.

@erkkikeranen Can you try this version? It should include a handling for identity providers.
https://github.com/adorsys/keycloak-config-cli/actions/runs/52260883

**Comment by erkkikeranen** [comment]
That was fast 😊 , will experiment latest on wednesday.

**Comment by erkkikeranen** [comment]
Hi, I can confirm the change is able to update my identity provider config. Thanks!
