### ISSUE TITLE
Docker image built for arm64 architecture

### ISSUE THREAD

**Issue by ialisyed** [adorsys/keycloak-config-cli#503]
Hi,

There is no docker image for macs with M1 chip. I have found a Keycloak image built on arm/64 arch and now I also need keycloak-config-cli to run on this architecture as well.

I believe a docker image build via arm/64 architecture would work fine for macs with m1 chips.

**Comment by jkroepke** [comment]
keycloak-config-cli is fully written in java. The (.jar) artifacts of keycloak-config-cli are architecture independent.

You can use use any openjdk arm64 as base image (like [adoptopenjdk/openjdk11:ubuntu-jre](https://hub.docker.com/layers/adoptopenjdk/openjdk11/ubuntu-jre/images/sha256-d9e88d0cf1c5188885da84c0c33374db114243753877a53abdcf5c86fe5d27e2?context=explore)) and put the jar into the image like here https://github.com/adorsys/keycloak-config-cli/blob/main/Dockerfile

I may have to figure out how I could build a multi arch image.

**Comment by ialisyed** [comment]
```
syed@Syeds-MacBook-Air keycloak-config-cli % sudo docker build -t saeed-keycloak-config-cli .
[+] Building 1.5s (6/6) FINISHED                                                
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 278B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/adoptopenjdk/openjdk11:ubuntu-  1.4s
 => [internal] load build context                                          0.0s
 => => transferring context: 2B                                            0.0s
 => CANCELED [1/2] FROM docker.io/adoptopenjdk/openjdk11:ubuntu-jre@sha25  0.0s
 => => resolve docker.io/adoptopenjdk/openjdk11:ubuntu-jre@sha256:259ec29  0.0s
 => => sha256:259ec2995b0c8ba1d809ba0fe5cb5770695b8ba2475 1.72kB / 1.72kB  0.0s
 => => sha256:4a9e98f93c9b655aa963697b1ba4aeb52bc2708cea290f3 953B / 953B  0.0s
 => => sha256:f088dbfdc118bf941a4b04b21a0a944f6cee6f0aac9 4.76kB / 4.76kB  0.0s
 => ERROR [2/2] COPY ./target/keycloak-config-cli.jar /app/                0.0s
------
 > [2/2] COPY ./target/keycloak-config-cli.jar /app/:
------
failed to compute cache key: "/target/keycloak-config-cli.jar" not found: not found

```


This is what I am getting when I am trying to build the image

**Comment by jkroepke** [comment]
Ye, to build the image, you have to run maven to built the artefacts first.

**Comment by jkroepke** [comment]
@ialisyed 

You could take a look at https://hub.docker.com/repository/docker/adorsys/keycloak-config-cli/tags?page=1&ordering=last_updated&name=v4.2.1-rc0

Looks like arm64 images are [easy](https://github.com/adorsys/keycloak-config-cli/commit/6e0c374b9040194a3fd26c88bc1d609d607571bf) to implement.

**Comment by mylesagray** [comment]
Thank you for this @jkroepke super quick turnaround!

**Comment by jkroepke** [comment]
@ialisyed 

Based on your feedback "This is what I am getting when I am trying to build the image"

The the dockerfile on main branch supports to build images while using jars from remote locations like

```bash
docker build -t keycloak-config-cli \ 
  --build-arg JAR=https://github.com/adorsys/keycloak-config-cli/releases/download/v4.2.0/keycloak-config-cli-15.0.1.jar .
```

That remove the requirement to build the project first.
