### ISSUE TITLE
invalidPasswordHistoryMessage when running keycloak-config-cli

### ISSUE THREAD

**Issue by borislav72** [adorsys/keycloak-config-cli#512]
And another problem that we have:

Using keycloak-config-cli we create realm and some users. For the realm we have defined password policy: one of the rules is for password history:

`
"passwordPolicy": "... and passwordHistory(3)"
`

When keycloak-config-cli is run  more that 3 times we get invalidPasswordHistoryMessage error.

keycloak-config-cli performs a checksum comparison, but this is done on the whole set of imported json files, correct?
I would think that the problem above can be solved if a checksum comparison is performed on each json file (flyway behavior). Have you thought of implementing such behaviour?

Do you have an idea how to solved the problem with user's password history?

Regards

**Comment by jkroepke** [comment]
> Do you have an idea how to solved the problem with user's password history?

You could set a initial password of a user

https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md#user---initial-password

In that case, the password is managed only on creation time.

**Comment by jkroepke** [comment]
The root issue is keycloak-config-cli has no chance to detect if a password needs to be changed or not. Currently, keycloak-config-cli sets the password all time.

**Comment by borislav72** [comment]
@jkroepke Thank you
