### ISSUE TITLE
Realm "defaultDefaultClientScopes" and "defaultOptionalClientScopes" are ignored

### ISSUE THREAD

**Issue by george-newby** [adorsys/keycloak-config-cli#513]
**Describe the bug**
The top level realm properties "defaultDefaultClientScopes" and "defaultOptionalClientScopes" are ignored. 

I found this out because I wanted to remove the default "web-origins" client scope as it substantially increased the size of my access token size which went over the chromes 4kb cookie size limit.

**To Reproduce**

1. Create test.json import file
```json
{
  "id": "test",
  "realm": "test",
  "defaultDefaultClientScopes": ["email"],
  "defaultOptionalClientScopes": ["address"]
}
````

2. Spin up fresh keycloak
```bash
docker run --rm \
    -p 8080:8080 \
    -e KEYCLOAK_USER=admin \
    -e KEYCLOAK_PASSWORD=admin \
    quay.io/keycloak/keycloak:13.0.1
```

3. Run keycloak-config-cli
```bash
docker run --rm \
    --network="host" \
    -v ${PWD}:/config \
    -e IMPORT_PATH=/config/test.json \
    -e KEYCLOAK_URL=http://localhost:8080/auth \
    -e KEYCLOAK_USER=admin \
    -e KEYCLOAK_PASSWORD=admin \
    adorsys/keycloak-config-cli:latest-13.0.1
```

4. Observe the Default Client Scopes in Keycloak
![image](https://user-images.githubusercontent.com/54625433/129944204-4468016a-d547-446e-833c-6f6334afc17c.png)

**Expected behavior**
I expect the Assigned Default Client Scopes to be only set to "email" and nothing less

**Environment:**
 - Keycloak Version: 13.0.1
 - keycloak-config-cli Version: 13.0.1
 - Java Version: 11
 - Docker Tag: latest-13.0.1

**Additional context**
This is due to https://issues.redhat.com/browse/KEYCLOAK-13951. The HTTP requests for getting and updating realms ignores the defaultDefaultClientScopes in the RealmRepresentation. This is also an issue with the client ```org.keycloak.admin.client.Keycloak```.

This could be worked around by manually adding/removing the default client scopes when updating a realm. The ```org.keycloak.admin.client.resource.RealmResource``` already has the methods to do it:
```java
@GET
@Produces(MediaType.APPLICATION_JSON)
@Path("default-default-client-scopes")
List<ClientScopeRepresentation> getDefaultDefaultClientScopes();

@PUT
@Path("default-default-client-scopes/{clientScopeId}")
void addDefaultDefaultClientScope(@PathParam("clientScopeId") String clientScopeId);

@DELETE
@Path("default-default-client-scopes/{clientScopeId}")
void removeDefaultDefaultClientScope(@PathParam("clientScopeId") String clientScopeId);
```

**Comment by jkroepke** [comment]
I may add a lot of test case here.

For example. If an existing client has `defaultClientScopes: group` and keycloak-config-cli tries to add `defaultDefaultClientScopes: group`, then this be result in a 409 Conflict and the keycloak log reports a SQL violation ...
