### ISSUE TITLE
Similarly named entities cause null pointer issues in StateRepository

### ISSUE THREAD

**Issue by ddowling-act** [adorsys/keycloak-config-cli#563]
### Current Behavior

Given two entities named, for example "client-a" and "client-a-test", the current code (ln 107 of de.adorsys.keycloak.config.repository.StateRepository

`        long attributeCount = customAttributes
                .entrySet()
                .stream()
                .filter(attribute -> attribute.getKey().startsWith(getCustomAttributeKey(entity) + "-"))
                .count();`

will return a non-zero value for "client-a" even if custom attributes only exist for "client-a-test".
This results in later code returning a null, which is passed upwards causing a null pointer exception in de.adorsys.keycloak.config.service.RoleImportService.lambda$getManagedClientRoles$4(RoleImportService.java:284) 

### Expected Behavior

Code should not error when two similarly named entities exist

### Environment

- Keycloak Version: 14.0.0
- keycloak-config-cli Version: tested with checkout of master, and /v4.3.0/keycloak-config-cli-15.0.2.jar
- Java Version: 8

### Anything else?

Suggested fixed implementation:
`        long attributeCount = customAttributes
                .entrySet()
                .stream()
                .filter(attribute -> attribute.getKey().matches(String.format("^%s-\\d+$", getCustomAttributeKey(entity))))
                .count();`

**Comment by jkroepke** [comment]
I'm trying to implement a test that triggers the NPE. can you provide an example?

**Comment by ddowling-act** [comment]
Hi @jkroepke, I can try, though I'm honestly not sure what has got it into the state where the null pointer is thrown further than what I've given above.

**Comment by ddowling-act** [comment]
In my case, the attribute "de.adorsys.keycloak.config.state-default-roles-client-{name}-test-0" is already present in the keycloak realm, and the lookup is being done for "de.adorsys.keycloak.config.state-default-roles-client-{name}-0"
The null pointer occurs because "public List<String> getState(String entity)" returns null when it should return a list, and this is because the get from the map returns null, which is then concatinated into the string "null", that is then converted to null when it's passed to the "fromJson" method, rather than converting into a list. So a unit test should be straight forward to write based on the above, but are you after information to write a component/integration level test instead?

**Comment by ddowling-act** [comment]
I'll also note that "de.adorsys.keycloak.config.state-default-roles-client-{name}-0" *does not* exist currently in the keycloak realm, hence the lookup returning null. I think if both did exist there would still be an issue though as the check for how many exist would return 2 instead of 1, so it would still fail while looking for "de.adorsys.keycloak.config.state-default-roles-client-{name}-1", but I'm not sure how that would behave with the concatenation. That would likely produce an actual list with a real entry and a null entry, which might not trigger a null pointer exception in the same way as the issue I'm encountering

**Comment by ddowling-act** [comment]
Below are the client representation in my realm file:
`{
      "clientId": "example-test",
      "surrogateAuthRequired": false,
      "enabled": true,
      "alwaysDisplayInConsole": false,
      "clientAuthenticatorType": "client-secret",
      "redirectUris": [
        "*"
      ],
      "webOrigins": [],
      "notBefore": 0,
      "bearerOnly": false,
      "consentRequired": false,
      "standardFlowEnabled": true,
      "implicitFlowEnabled": false,
      "directAccessGrantsEnabled": true,
      "serviceAccountsEnabled": true,
      "publicClient": false,
      "frontchannelLogout": false,
      "protocol": "openid-connect",
      "attributes": {
        "saml.assertion.signature": "false",
        "saml.multivalued.roles": "false",
        "saml.force.post.binding": "false",
        "saml.encrypt": "false",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "saml.authnstatement": "false",
        "saml.server.signature": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "saml.onetimeuse.condition": "false"
      },
      "authenticationFlowBindingOverrides": {},
      "fullScopeAllowed": true,
      "nodeReRegistrationTimeout": -1,
      "protocolMappers": [
        {
          "id": "14ff80cc-5dbe-40c1-ab4c-184a2404776c",
          "name": "given name",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-property-mapper",
          "consentRequired": false,
          "config": {
            "userinfo.token.claim": "true",
            "user.attribute": "firstName",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "given_name",
            "jsonType.label": "String"
          }
        },
        {
          "id": "130aedab-c5a6-4131-82e6-432f685f9bd9",
          "name": "username",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-property-mapper",
          "consentRequired": false,
          "config": {
            "userinfo.token.claim": "true",
            "user.attribute": "username",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "preferred_username",
            "jsonType.label": "String"
          }
        },
        {
          "id": "c4baf2e5-5297-47bd-b350-40ada217cb2d",
          "name": "Client ID",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usersessionmodel-note-mapper",
          "consentRequired": false,
          "config": {
            "user.session.note": "clientId",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "clientId",
            "jsonType.label": "String"
          }
        },
        {
          "id": "a43433f0-0001-4177-9654-eadf99523e48",
          "name": "family name",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-property-mapper",
          "consentRequired": false,
          "config": {
            "userinfo.token.claim": "true",
            "user.attribute": "lastName",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "family_name",
            "jsonType.label": "String"
          }
        },
        {
          "id": "895b9a82-d70d-4a06-a087-042d217b345b",
          "name": "email",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-property-mapper",
          "consentRequired": false,
          "config": {
            "userinfo.token.claim": "true",
            "user.attribute": "email",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "email",
            "jsonType.label": "String"
          }
        },
        {
          "id": "113aa5c0-c2d4-420d-9b6c-cbcd574feb47",
          "name": "role list",
          "protocol": "saml",
          "protocolMapper": "saml-role-list-mapper",
          "consentRequired": false,
          "config": {
            "single": "false",
            "attribute.nameformat": "Basic",
            "attribute.name": "Role"
          }
        },
        {
          "id": "81a27cfe-e017-4caf-b099-a16f8f043ea6",
          "name": "full name",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-full-name-mapper",
          "consentRequired": false,
          "config": {
            "id.token.claim": "true",
            "access.token.claim": "true"
          }
        },
        {
          "id": "a92d3746-fbd7-429c-bf8f-c9ab16c016b9",
          "name": "Client IP Address",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usersessionmodel-note-mapper",
          "consentRequired": false,
          "config": {
            "user.session.note": "clientAddress",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "clientAddress",
            "jsonType.label": "String"
          }
        },
        {
          "id": "671c5ac4-ba02-4e6b-bd0c-2b97976438ac",
          "name": "Client Host",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usersessionmodel-note-mapper",
          "consentRequired": false,
          "config": {
            "user.session.note": "clientHost",
            "id.token.claim": "true",
            "access.token.claim": "true",
            "claim.name": "clientHost",
            "jsonType.label": "String"
          }
        }
      ],
      "defaultClientScopes": [
        "web-origins",
        "roles"
      ],
      "optionalClientScopes": [
        "offline_access",
        "microprofile-jwt"
      ]
    }`

And then for roles->clients it has 
`"example-test": [],`

Looking into this further then, the "example" client exists in the current keycloak but not in my realm file that is being applied. Perhaps this is the part that you are missing when attempting to test? Assuming the application should then be trying to remove that untracked client?

**Comment by jkroepke** [comment]
> That would likely produce an actual list with a real entry and a null entry, which might not trigger a null pointer exception in the same way as the issue I'm encountering

I got the same, looks like the null value are converted on String.join. Since the delimiter is empty, it wont have any effect.

Anyway, I will apply your suggestion, since this feels more correct.

> Assuming the application should then be trying to remove that untracked client?

Only clients create by keycloak-config-cli will deleted by keycloak-config-cli.
