### ISSUE TITLE
Behavior for multiple realms in one yaml file is not defined

### ISSUE THREAD

**Issue by tobilarscheid** [adorsys/keycloak-config-cli#593]
### Current Behavior

*GIVEN*
A yaml file with multiple realms in it, e.g.
```yaml
realm: first
...
---
realm: second
...
```

*WHEN*
1. I import this file for the first time
2. I make changes to this file and import it later

*THEN*
1. Everything works as expected
2. Changes are not imported

### Expected Behavior

Initial load and subsequent updates should work

### Environment

- Keycloak Version: 15.0.2
- keycloak-config-cli Version: 4.2.2
- Java Version: 11

**Comment by tobilarscheid** [comment]
Alright, this was impressive! Thank you!!

**Comment by jkroepke** [comment]
@tobilarscheid I hope it fixed you needs.
