### ISSUE TITLE
README & Features documents are out of date.

### ISSUE THREAD

**Issue by SomeDeveloper13** [adorsys/keycloak-config-cli#626]
### Problem Statement

README & Features markdown documents are out of date by a full release.

### Proposed Solution

Update the README & Feature documents to match the work that has been done.

### Environment

- Keycloak Version: N/A
- keycloak-config-cli Version: 4.6.1
- Java Version: N/A

### Acceptance Criteria

- [] As a User, I should see the latest information in the README & features markdown files.

**Comment by jkroepke** [comment]
Hi, 

looking at README: Can you explain what is out of date here?
