### ISSUE TITLE
Properties from files does not seem to be working.

### ISSUE THREAD

**Issue by ianwallen** [adorsys/keycloak-config-cli#634]
### Current Behavior

I'm trying to use the configtree as indicated in the reame.md documentation. (https://github.com/adorsys/keycloak-config-cli#configure-properties-values-through-files)

I attempted to create a property replacement using something like $(test.configtree.value) and I can verify that the property is loaded correctly however it does not seem to work.

### Expected Behavior

I expect that the regular properties could be used in the substitution logic but it seem to generate errors.

I looked for a sample that used regular properties but I cannot find any in the documentation.  I only found system properties usage.

### Steps To Reproduce

```markdown
I modified one of the unit test to reproduce the issue. The changes are located in the following commit.

https://github.com/ianwallen/keycloak-config-cli/commit/ac0ff495099e6ad0122316ca5539f2bfcc963526
```

### Environment

- Keycloak Version: 16 based on unit test.
- keycloak-config-cli Version: main branch
- Java Version: [e.g. 11]

### Anything else?

If it is identified that I'm doing the logic incorrectly then I would suggest that a unit test or other example be created to show how the properties from files is supposed to work.

**Comment by jkroepke** [comment]
Hi,

there is already a unit test to test system properties. If you take a look at https://github.com/adorsys/keycloak-config-cli#variable-substitution, you may see that

```
System Property:       $(sys:user.dir)
```

have a prefix `sys`. `$(sys:test.configtree.value)` should work while `$(test.configtree.value)` not.
