### ISSUE TITLE
Make deletion of resources configurable for clients with remote resource management

### ISSUE THREAD

**Issue by martinofner13** [adorsys/keycloak-config-cli#641]
### Problem Statement

We have a client with activated authorization. The client can dynamically add resources - "Remote Resource Management" is activated
If we change the config (i.e. reconfigure default client scopes) and run keycloak-config-cli, all resources that have been created are purged.

The related source code is in `ClientImportService.java` (line 292):
```
removeAuthorizationResources(realmName, client,
existingAuthorization.getResources(), authorizationSettingsToImport.getResources());
```

### Proposed Solution

Option 1:
* Deactivate resource deletion automatically if client has "Remote Resource Management" activated

Option 2:
* Add command line parameter to deactivate purging of resources

### Environment

- Keycloak Version: 16.0.0
- keycloak-config-cli Version: 4.5.0
- Java Version: Java 14

### Acceptance Criteria

- As a user I can control if existing resources of an client with activated authorization are deleted or not

**Comment by jkroepke** [comment]
How keycloak-config-cli could detect if client has "Remote Resource Management" activated?

**Comment by martinofner13** [comment]
This information is stored in `allowRemoteResourceManagement`

See sample config file:

```
{
  "id": "<id>",
  "realm": "<realm>",
  "clients": [
    {
      "clientId": "<clientId>",
       ...
      "authorizationSettings": {
        "allowRemoteResourceManagement": true,
        ...
       }
    }
  ]
}
```

**Comment by jkroepke** [comment]
Its a use-case to add additional resources through keycloak-config-cli? For example, keycloak-config-cli should only delete resource that coming from keycloak-config-cli?

Or resource are coming exclusively from remote? In this case, the could exclude the whole handling of resources, if `allowRemoteResourceManagement==true` I'm asking independently from your case, since I do not know this feature.

**Comment by martinofner13** [comment]
Yes - I can imagine this use case. 
- Provide (static) resources via `keycloak-config-cli` (i.e. endpoints with url like `/api/admin`)
- Dynamically created resources by the client (i.e. photo albums with url like `/api/albums/123`)

It makes sense that `keycloak-config-cli` manages "own" resources, but don't delete the other ones - if `allowRemoteResourceManagement` is enabled.

**Comment by jkroepke** [comment]
> It makes sense that keycloak-config-cli manages "own" resources, but don't delete the other ones

I will open a PR for this. But would enable this, not matter which value `allowRemoteResourceManagement` has.

**Comment by jkroepke** [comment]
Hi @martinofner13 

while I adding some test around the new feature, I also want to create resources through the UMA endpoint to verify that keycloak-config-cli are not delete them. I'm using [keycloak authz client](https://www.keycloak.org/docs/latest/authorization_services/#_service_client_api) to archive that.

Currently, I'm getting an error while using the client

```
org.keycloak.authorization.client.AuthorizationDeniedException: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 403 / Forbidden / Response from server: {"error":"invalid_scope","error_description":"Requires uma_protection scope."}
```

This is my realm file:

https://github.com/adorsys/keycloak-config-cli/blob/manage-resources/src/test/resources/import-files/clients/11_update_realm__add_authorization.json

and I'm using the `auth-moped-client` client to authenticate. Do you have an idea how I could solve this problem?

**Comment by jkroepke** [comment]
Hi @martinofner13 

are you able to test the pull-request from https://github.com/adorsys/keycloak-config-cli/pull/646 ?
