### ISSUE TITLE
Future of keycloak-config-cli

### ISSUE THREAD

**Issue by jkroepke** [adorsys/keycloak-config-cli#686]
Hi all,

in few weeks, I will have a new job in a new company. keycloak-config-cli will retain in the adorsys GitHub organization. Since I'll lose my permissions here, and I'm no longer maintain or responsible for [adorsys/keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli). 

adorsys will do the future maintenance here.

Thanks.

**Comment by RVSO-NC** [comment]
Thanks for your great work! :)
Hope adorsys will keep it up.

**Comment by jkroepke** [comment]
I get the info that someone from adorsys will start to maintain it this week.

**Comment by RVSO-NC** [comment]
That's brillant! Thank you so much 👍

**Comment by ic2hrmk** [comment]
@jkroepke, thank you for the support you were doing all this time!
Good luck with your new position, I hope that would be a great place :)

**Comment by st3v0rr** [comment]
Hello,
once again... @jkroepke thanks so much! :-)

I released a v5.2.0 with support for keycloak 18. (also once again thanks to @thomasdarimont)

As already mentioned in https://github.com/adorsys/keycloak-config-cli/pull/718 ...
It is still in clarification who at adorsys will maintain this project in the future.

In the meantime I will try to keep up with the opened issues and also try to be available for your questions.
Please be aware that I'm doing this more or less between my work on customer projects so sometimes the communication may take a while :-(

Best regards!

**Comment by SvenWinkler** [comment]
Farewell @jkroepke + thx for your great work. I wish you all the best and good luck :-)
@thomasdarimont: Your accompany is welcome, so let's get in touch. I will reach out to you.
