### ISSUE TITLE
Small documentation bug

### ISSUE THREAD

**Issue by jeromewaibel** [adorsys/keycloak-config-cli#713]
### Current Behavior

This

keycloak-config-cli supports variable substitution of config files. This could be enabled by **import.var-substitution=true** (disabled by default).

should be changed to

keycloak-config-cli supports variable substitution of config files. This could be enabled by **import.var-substitution.enabled=true** (disabled by default).

as stated correctly several lines later. Cost me 30 minutes to figure out why this setting did not work.

### Environment

- Keycloak Version: [e.g. 10.0.1]
- keycloak-config-cli Version: [e.g. 1.4.0]
- Java Version: [e.g. 11]

**Comment by st3v0rr** [comment]
Hi @jeromewaibel 
thanks for your hint and sorry for this issue.
I changed the regarding property in the readme to the correct value.
