### ISSUE TITLE
Inclusion of "attributes" in update payload resets unrelated properties

### ISSUE THREAD

**Issue by SilentGert** [adorsys/keycloak-config-cli#728]
### Current Behavior

We had trouble seeing the Keycloak admin UI after the update to version 18. Setting the `frontendUrl` realm attribute on the master realm via DB query helped fix the issue.
Now, I wanted to roll out the change to some other instances using Keycloak config CLI instead of a DB query.

When I update the master realm including the `attributes` property in the JSON payload, a lot of the master realm configuration properties get reset even though I didn't mention them.

I did a realm export before the update
```
  "displayName": "Keycloak",
  "displayNameHtml": "<div class=\"kc-logo-text\"><span>Keycloak</span></div>",
  "defaultSignatureAlgorithm": "RS256",
  "maxFailureWaitSeconds": 900,
  "minimumQuickLoginWaitSeconds": 60,
  "waitIncrementSeconds": 60,
  "quickLoginCheckMilliSeconds": 1000,
  "maxDeltaTimeSeconds": 43200,
  "failureFactor": 30,
  "browserSecurityHeaders": {
    "contentSecurityPolicyReportOnly": "",
    "xContentTypeOptions": "nosniff",
    "xRobotsTag": "none",
    "xFrameOptions": "SAMEORIGIN",
    "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
    "xXSSProtection": "1; mode=block",
    "strictTransportSecurity": "max-age=31536000; includeSubDomains"
  },
```

And after the update, `displayName`, `displayNameHtml` and `defaultSignatureAlgorithm` are missing in the export and some others have been reset
```
  "maxFailureWaitSeconds": 0,
  "minimumQuickLoginWaitSeconds": 0,
  "waitIncrementSeconds": 0,
  "quickLoginCheckMilliSeconds": 0,
  "maxDeltaTimeSeconds": 0,
  "failureFactor": 0,
  "browserSecurityHeaders": {},
```

On the positive side, `attributes.frontendUrl` was set properly. 

As soon as I exclude `attributes` from the JSON payload, the update behavior works as expected again. The other configuration properties are not changed unless I mention them in the payload.

### Expected Behavior

When I update `attributes`, I only expect the `attributes` that I mentioned to change and no unrelated configuration properties. 

### Steps To Reproduce

1. Export the master realm configuration
2. Update the master realm configuration with the following payload
```markdown
{
  "id": "master",
  "realm": "master",
  "attributes": {
    "frontendUrl": "https://keycloak.example.com/auth"
  }
}
```
3. Export the master realm configuration again

Several configuration properties have been reset, but not all of them.

I use the following parameters when calling the CLI
```
--keycloak.url=$KEYCLOAK_URL \
--keycloak.password=$KEYCLOAK_PASSWORD \
--import.files.locations="./master-realm-update.json" \
--import.var-substitution.enabled=true
```

### Environment

- Keycloak Version: 18.0.0
- keycloak-config-cli Version: 5.2.0
- Java Version: 11

**Comment by st3v0rr** [comment]
Hi @SilentGert 
would it be possible four you, to provide the exported realm json with your additional change of the frontendUrl?
For example...
`
{
  "id": "master",
  "realm": "master",
  "attributes": {
    "frontendUrl": "https://keycloak.example.com/auth"
  }
  "displayName": "Keycloak",
  "displayNameHtml": "<div class=\"kc-logo-text\"><span>Keycloak</span></div>",
  "defaultSignatureAlgorithm": "RS256",
  "maxFailureWaitSeconds": 900,
  "minimumQuickLoginWaitSeconds": 60,
  "waitIncrementSeconds": 60,
  "quickLoginCheckMilliSeconds": 1000,
  "maxDeltaTimeSeconds": 43200,
  "failureFactor": 30,
  "browserSecurityHeaders": {
    "contentSecurityPolicyReportOnly": "",
    "xContentTypeOptions": "nosniff",
    "xRobotsTag": "none",
    "xFrameOptions": "SAMEORIGIN",
    "contentSecurityPolicy": "frame-src 'self'; frame-ancestors 'self'; object-src 'none';",
    "xXSSProtection": "1; mode=block",
    "strictTransportSecurity": "max-age=31536000; includeSubDomains"
  },
  ...
}
`

In detail...
We try to figure out deltas on the different Objects that are sent to keycloak with our cli tool.
When you remove all attributes and only leave the ones you want to change it is mentioned as a delta.
Fields that are no longer provided are set to keycloaks default value (e.g. null, 0, "", ...). In some cases delta checks are done with checksums, in other cases we try to achieve that with equality checks.
If you provide less data to import we have no algorithm that tells keycload to keep unprovided data.

**Comment by SilentGert** [comment]
@st3v0rr thanks for your quick answer. 
So do I get it right that the behavior is kind of expected then due to a lack of more data in the payload? 
I was honestly surprised that the behavior changes significantly by just using `attributes` in the payload. I've sent request which included only `displayName` before and they wouldn't change any other property. That's why it looked like a bug to me.

Is there by any chance a flag I can set to tell the CLI to keep unprovided data?

In my use case we do not store the whole exported realm configuration separately. Besides the master we have lots of dynamically created realms and I was kind of happy when I saw after some initial experimentation that I can apply templates with a patch semantic and only include the changes I wanted to make.
