### ISSUE TITLE
Unable to invoke request

### ISSUE THREAD

**Issue by jankomuzykant19** [adorsys/keycloak-config-cli#738]
### Current Behavior

When trying to connect to Keycloak it ends up with:
Could not connect to keycloak in 12 seconds: RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:20180 [localhost/127.0.0.1] failed: Connection refused (Connection refused)

### Expected Behavior

keycloak-config-cli successfully connects to Keycloak

### Steps To Reproduce

```markdown
Running following command:
docker run \
    -e KEYCLOAK_URL="http://localhost:20180/auth" \
    -e KEYCLOAK_USER="admin" \
    -e KEYCLOAK_PASSWORD="admin" \
    -e KEYCLOAK_LOGINREALM="selfservice" \
    -e KEYCLOAK_CLIENTID="admin-cli" \
    -e KEYCLOAK_AVAILABILITYCHECK_ENABLED=true \
    -e KEYCLOAK_AVAILABILITYCHECK_TIMEOUT=12s \
    -e LOGGING_LEVEL_ROOT=info \
    -e IMPORT_FILES='/home/janstawinski/Desktop/TestConfig/config/*.json' \
    -v /home/janstawinski/Desktop/TestConfig/config:/config \
    adorsys/keycloak-config-cli:v3.4.0-13.0.0

Path to config files, credentials and realm name are correct.
```

### Environment

- Keycloak Version: 18.0
- keycloak-config-cli Version: latest
- Java Version: 11

**Comment by luisscholl** [comment]
What fixed your issue?

**Comment by Froctnow** [comment]
The same issue
