### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by skhro87** [adorsys/keycloak-config-cli#741]
### Current Behavior

Small Typo in the `README`:

Under `Spring boot options` it says
`--loging.level.root` which should be `--logging.level.root`

Thanks for your work on this great tool! 

### Expected Behavior

Under `Spring boot options`:
`--loging.level.root` should be `--logging.level.root`

### Environment

- Keycloak Version: [e.g. 10.0.1]
- keycloak-config-cli Version: [e.g. 1.4.0]
- Java Version: [e.g. 11]

**Comment by st3v0rr** [comment]
Hi @skhro87,
thank you very much for your feedback :-)
That was an easy one. Fixed it.
