### ISSUE TITLE
[Advice] Development workflow with keycloak-config-cli

### ISSUE THREAD

**Issue by ederparaiso** [adorsys/keycloak-config-cli#743]
Hi,

I'm new to keycloak and keycloak-config-cli and I'm trying to understand how to use this cli in my development cycle. 

Taking [moped.json](https://github.com/adorsys/keycloak-config-cli/blob/main/contrib/example-config/moped.json) as example, how this file was could be generated? 
The moped realm was exported manually from keycloak through "Partial Export" feature on keycloak admin console / kc.sh export using command line?

Considering docs on README,

> The config files are based on the keycloak export files. You can use them to re-import your settings. But keep your files as small as possible. Remove all UUIDs and all stuff which is default set by keycloak.

After manual realm export, should I manually sanitize exported json removing all uuuid fields and all other general/default configs that I don't want to be part of import process?

Thanks in advance

**Comment by st3v0rr** [comment]
Hi @ederparaiso ,
basically you can start with the provided example if you have a green field approach. 
If you already have bootstrapped keycloak instances just start with them and export the needed data.
You can also have a look on the generate-export-realm.sh in contrib/scripts folder of this git repo.
Unfortunately we have no tool that automates the sanitization.

Best regards

**Comment by ederparaiso** [comment]
Thanks for your attention @st3v0rr ! I'll check this script and define the best approach to my needs.

**Comment by kantum** [comment]
Where can we find documentation about the "all stuff" in `Remove all UUIDs and all stuff which is default set by keycloak.`
