### ISSUE TITLE
otpPolicyAlgorithm ignored

### ISSUE THREAD

**Issue by daniel-shuy** [adorsys/keycloak-config-cli#847]
### Current Behavior

When running with:
```yml
otpPolicyAlgorithm: "HmacSHA512"
```

The OTP hash algorithm (Authentication -> Policies -> OTP Policy) is not updated

### Expected Behavior

The OTP hash algorithm should be updated to `SHA512`

### Steps To Reproduce

```markdown
1. Run keycloak-config-cli with the config:

otpPolicyAlgorithm: "HmacSHA512"

2. Check the OTP hash algorithm (Authentication -> Policies -> OTP Policy) value
```

### Environment

- Keycloak Version: `19.0.3`/`21.0.1` (tested with both)
- keycloak-config-cli Version: `5.6.1`

**Comment by dominiktopp** [comment]
seems like otpPolicyCodeReusable does also not work. It is always reset to false when importing our config using keycloak-config-cli
