### ISSUE TITLE
Support realms as configmaps as well

### ISSUE THREAD

**Issue by brunocascio** [adorsys/keycloak-config-cli#866]
### Problem Statement

In our process, we are using SealedSecret and we don't allow the kind Secret on our code, for this reason, would be great if we can configure the realms with configmaps instead of secrets.
The configmap will have the env variable which reference the secret afterwards, so no sensible data will be stored on the configmap

### Proposed Solution

- Support realms configs as configmaps also

### Environment

N/A

### Acceptance Criteria

- [ ] As a user, I can switch between secret to configmaps for realms configurations

**Comment by manuschillerdev** [comment]
this should already be possible (at least with the bitnami helm charts it is):
https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L992 

We use that on a regular basis like so:

```keycloak-realm-config.yaml
# templates/keycloak-realm-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  namespace: {{ .Release.Namespace }}
data:
  {{ tpl (.Files.Glob "config/*.json").AsConfig . | indent 2 }}
```

```values.yaml
# values.yaml
keycloak:
  keycloakConfigCli:
    enabled: true
    existingConfigmap: keycloak-realm-config
```

**Comment by Motouom** [comment]
Hello, @brunocascio. 

Try the solution proposed above and give feedback if it works for you.
