### ISSUE TITLE
Client authorizationSettings are not imported with config-cli 5.6.1 on Quarkus Keycloak 21.1.1

### ISSUE THREAD

**Issue by an966** [adorsys/keycloak-config-cli#876]
[attachments.zip](https://github.com/adorsys/keycloak-config-cli/files/11636368/attachments.zip)
### Current Behavior

When we import our realm JSON file with the adorsys config-cli, the authorizationSettings defined on the realm-management client  are not imported. 

### Expected Behavior

With adorsys config-cli version 4.3.0 and Wildfly Keycloak 15.0.2 the authorizationSettings defined on the realm-management client  are imported as expected.

### Steps To Reproduce

```markdown
Start Quarkus Keycloak 21.1.1 (Features token-exchange & admin_fine_grained_authz enabled)

Import the attached realm JSON file (test-realm.json) with config-cli 5.6.1 (please see attached application.properties for the config-cli configuration)

Login to the Keycloak Admin Console

Navigate to Identity Provider > test-idp > Permission (*/auth/admin/master/console/#/test/identity-providers/keycloak-oidc/keycloak-oidc/permissions)

Check wether the permissions are enabled and
the token-exchange is configured (in my case the permissions are disabled and the token-exchange is not configured) 

Navigate to Clients > token-exchange > Permissions (*/auth/admin/master/console/#/test/clients/client_id/permissions)

Check wether the permissions are enabled and
the token-exchange is configured (in my case the permissions are disabled and the token-exchange is not configured)
```

### Environment

Environment (not working)
- Keycloak Version: 21.1.1
- keycloak-config-cli Version: 5.6.1
- Java Version: 11

Environment (working)
- Keycloak Version: 15.0.2
- keycloak-config-cli Version: 4.3.0
- Java Version: 11

### Anything else?

[attachments.zip](https://github.com/adorsys/keycloak-config-cli/files/11624785/attachments.zip)

**Comment by an966** [comment]
@jkroepke comment on ticket https://github.com/adorsys/keycloak-config-cli/issues/648 that there are some issues with the Quarkus distribution regarding the import of authorization policies on realm-management client:

https://github.com/adorsys/keycloak-config-cli/issues/648#issuecomment-1054311876

**Comment by jkroepke** [comment]
@an966 I do not have any access here anymore, since I leaved the company.
