### ISSUE TITLE
Error when creating new realm role without mentioning default role

### ISSUE THREAD

**Issue by plachta11b** [adorsys/keycloak-config-cli#884]
### Current Behavior

Error when creating new realm role due to keycloak-config-cli trying to remove default realm role.

Using [test resource](https://github.com/adorsys/keycloak-config-cli/blob/main/src/test/resources/import-files/roles/01_update_realm__add_realm_role.json) to add role to realm produced:

```
ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : HTTP 400 Bad Request
```
Before the error:
```
DEBUG 1 --- [           main] d.a.k.config.service.RoleImportService   : Delete realm-level role 'default-roles-my-realm' in realm 'my-realm'
```

### Expected Behavior

Keycloak does not touch the default role. And adds new roles to the currently configured.

### Environment

- Keycloak Version: [21.1.1]
- keycloak-config-cli Version: [5.6.1]
- Java Version: [17.0.6]

### Anything else?

I need a general solution that could configure multiple Keycloak instances where I have no control over basic/default/starting configuration.

**Comment by jonasvoelcker** [comment]
Hi @st3v0rr,

this issue should be solved now 😉

**Comment by plachta11b** [comment]
@jonasvoelcker It works now. Thank you.
