### ISSUE TITLE
Error when updating users with credentials

### ISSUE THREAD

**Issue by greibl-SIT** [adorsys/keycloak-config-cli#904]
### Current Behavior

When updating my realm. I get a 400 Status Code from my Keycloak instance for all users that have credentials in their yaml File.
The credentials didn't change in the YAML or through the UI since they were created.

Keycloak logs the following error:
`Could not update user!: org.keycloak.models.ModelException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.keycloak.models.jpa.entities.CredentialEntity#558dd05e-26f2-4609-b1d3-745eac0800f2]`

### Expected Behavior

Since the credentials didn't change the configuration is applied

### Environment

- Keycloak Version: 21.1.1
- keycloak-config-cli Version: v5.6.2-SNAPSHOT
- Java Version: 11.0.19

### Anything else?

Keycloak log:
[Explore-logs-2023-07-26 09_50_54.txt](https://github.com/adorsys/keycloak-config-cli/files/12169453/Explore-logs-2023-07-26.09_50_54.txt)

keycloak-config-cli log:
[keycloak-cli-logs.txt](https://github.com/adorsys/keycloak-config-cli/files/12169534/keycloak-cli-logs.txt)

**Comment by jonasvoelcker** [comment]
Hi @greibl-SIT, optimistic locking is a concept to ensure that nobody changed the record between read and update, there might be some bug that writes into this user twice without using the changed entity for the second call. Could you try again with a recent version of this tool?

**Comment by Motouom** [comment]
Hello @greibl-SIT.

You can try using these Environments:
keycloak-config-cli: 6.1.6-25.0.1.
Keycloak: 25.0.1

one recent version of KC-CLI and your problem will be solved
