### ISSUE TITLE
Flag to no delete missing entries?

### ISSUE THREAD

**Issue by xgp** [adorsys/keycloak-config-cli#908]
### Problem Statement

I'd like to allow admins to create entities (e.g. IdPs, Authentication Flows) using the Keycloak Admin UI that are a superset of what is in the realm config json I use with keycloak-config-cli.

Is it currently possible to tell keycloak-config-cli not to delete entities it doesn't have in the config?

### Proposed Solution

Essentially this feature would be to add elements in the config that do not exist in the realm. Update elements that do not match between the config and realm. But **do not** delete elements that exist in the realm but not the config.

### Environment

- Keycloak Version: [e.g. 10.0.1]
- keycloak-config-cli Version: [e.g. 1.4.0]
- Java Version: [e.g. 11]

**Comment by f11h** [comment]
Check the documentation: https://github.com/adorsys/keycloak-config-cli/blob/main/docs/MANAGED.md
Your case is perfectly covered ;)

**Comment by xgp** [comment]
Thanks for the pointer @f11h I didn't initially find this in the docs.

**Comment by xgp** [comment]
Looks like it uses "Spring Relaxed Binding", so the solution is to remove the hyphen altogether. 

`--import.managed.authentication-flow=no-delete` becomes `IMPORT_MANAGED_AUTHENTICATIONFLOW=no-delete`
