### ISSUE TITLE
Client Protocol Mapper config not being updated

### ISSUE THREAD

**Issue by cbett** [adorsys/keycloak-config-cli#93]
After creating my client with a Mapper, I can't seem to update it again.
Specifically i'm trying to update the `multivalued` property to `true` in the protocolMapper config.  I don't see any errors - it's just that the value is still not enabled in the UI.  Here is a snapshot of the JSON file being uploaded...
```
"protocolMappers": [
        {
          "name": "BranchCodeMapper",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-usermodel-attribute-mapper",
          "consentRequired": false,
          "config": {
            "aggregate.attrs": "false",
            "userinfo.token.claim": "true",
            "multivalued": "true",
            "user.attribute": "branch",
            "id.token.claim": "false",
            "access.token.claim": "true",
            "claim.name": "branch",
            "jsonType.label": "String"
          }
        }
```

**Comment by jkroepke** [comment]
Hi!

thanks for your report. Do you talk about `protocolMappers` in `clientScopes`?

**Comment by cbett** [comment]
Hi, No it is a Mapper inside the client itself.  Specifically the "ProtocolMappers" property as part of the [ClientRepresentation](https://www.keycloak.org/docs-api/4.8/javadocs/org/keycloak/representations/idm/ClientRepresentation.html#protocolMappers)

**Comment by jkroepke** [comment]
I'm asking because clientScopes has also protocolMappers..

https://www.keycloak.org/docs-api/4.8/javadocs/org/keycloak/representations/idm/ClientScopeRepresentation.html#protocolMappers

I will have look into it.

**Comment by jkroepke** [comment]
Hi @cbett 

#95 should fix this problem. Could you verify it?

https://github.com/adorsys/keycloak-config-cli/actions/runs/131408453

Caution: the master branch contains a lot of changes for the next 2.0 version. See https://github.com/adorsys/keycloak-config-cli/blob/master/CHANGELOG.md for all changes.

**Comment by cbett** [comment]
Hi @jkroepke 
Yes I can confirm that this is now fixed.
Thanks ever so much for your speedy response.  I will close the issue.

**Comment by jkroepke** [comment]
Thanks for your response.

>  I will close the issue.

Next time, please let the issue open. Then Github will assign the linked pull request as fix.

**Comment by cbett** [comment]
Of course, sorry for that.
