### ISSUE TITLE
client roles case sensitivity

### ISSUE THREAD

**Issue by mattlong-finocomp** [adorsys/keycloak-config-cli#940]
### Current Behavior

I was attempting to import a realm over the top of an existing realm to apply changes that had been made.
Someone had manually created a client role of "Admin" under a client using the keycloak admin UI.
It was subsequently added to the realm file applied by config cli as "admin".
When attempting to apply the change the only error was the following in the logs:
`2023-11-06 02:18:06.823 ERROR 1 --- [           main] d.a.k.config.KeycloakConfigRunner        : HTTP 409 Conflict`
After updating the logging level to trace I found it was because Keycloak was saying that the client role already existed.

### Expected Behavior

If keycloak treats client roles as case insensitive, then the config cli should try to match case insensitive too.

The error message reported should be more useful to someone looking in the logs without having to increase the logging level.

Note that the message reported by the server wouldn't be helpful on it's own as it doesn't indicate what resource had the issue.

### Steps To Reproduce

```markdown
Create a realm config file that includes at least 1 client role that begins with an upper case character.
Apply the config file using the config cli.
Update the client role in the realm config file to have a lower case first character. 
Apply the updated config file using the config cli.
```

### Environment

- Keycloak Version: 20.0.3
- keycloak-config-cli Version: 5.6.1-20.0.5
- Java Version: Whatever version is in the docker image

**Comment by Motouom** [comment]
Hello @mattlong-finocomp.

I have use your steps 
```
Create a realm config file that includes at least 1 client role that begins with an upper case character.
Apply the config file using the config cli.
Update the client role in the realm config file to have a lower case first character. 
Apply the updated config file using the config cli.
```
 and thesame environment 
 ```
Keycloak Version: 20.0.3
keycloak-config-cli Version: 5.6.1-20.0.5
Java Version: Whatever version is in the docker image
```

here are the json files that i used to check the issue of the case sensitivity

json import with an upper case client role
```json
{
  "realm": "test-realm",
  "enabled": true,
  "clients": [
    {
      "clientId": "test-client",
      "enabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "test-client-secret",
      "redirectUris": ["https://example.com/*"],
      "webOrigins": ["https://example.com"],
      "publicClient": false,
      "protocol": "openid-connect"
    }
  ],
  "roles": {
    "client": {
      "test-client": [
        {
          "name": "TestRole",
          "description": "A test role with an uppercase first character"
        }
      ]
    }
  }
}
```
![Image](https://github.com/user-attachments/assets/4d159996-45a7-43b8-9f96-43a5ecdbd0b2)

Now json import with an lower case client role.

```json
{
  "realm": "test-realm",
  "enabled": true,
  "clients": [
    {
      "clientId": "test-client",
      "enabled": true,
      "clientAuthenticatorType": "client-secret",
      "secret": "test-client-secret",
      "redirectUris": ["https://example.com/*"],
      "webOrigins": ["https://example.com"],
      "publicClient": false,
      "protocol": "openid-connect"
    }
  ],
  "roles": {
    "client": {
      "test-client": [
        {
          "name": "testRole",
          "description": "A test role with a lowercase first character"
        }
      ]
    }
  }
}
```
![Image](https://github.com/user-attachments/assets/7c563f7e-d9de-47a2-af44-452fb7352eda)


I gues you should probably check how your configurations in your import files are made and then give us a feedback if everything works for you as well
