### ISSUE TITLE
Add a way to import localizations message bundles

### ISSUE THREAD

**Issue by antikalk** [adorsys/keycloak-config-cli#945]
### Problem Statement

As far as I know there is currently no way to import the localization message bundles with keycloak-config-cli. 

You are able to enable internationalization, set the supported locales and default locale, but providing custom message bundles is not possible. This would be a cool feature to add.

### Proposed Solution

Support a new property `messageBundles` in the realm json which could look like this:

```json
{
  ...
  "messageBundles": {
    "de": {
      "hello": "Hallo",
      "world": "Welt"
      ...
    },
    "en": {
      "hello": "Hello",
      "world": "World"
      ...
    }
  }
}
```

For each locale in messageBundles post the content of the object to the corresponding locale endpoint, e.g.:
`POST realms/$realm/localization/de`
Body:
```json
{
  "hello": "Hallo",
  "world": "Welt"
  ...
}
```
and
`POST realms/$realm/localization/en`
Body:
```json
{
  "hello": "Hello",
  "world": "World"
  ...
}
```

### Environment

- Keycloak Version: [e.g. 22.0.5]
- keycloak-config-cli Version: [5.9.0]

**Comment by antikalk** [comment]
@st3v0rr sorry for bothering you, but is there any chance we could get that feature in? I created a PR some time ago, that allows for adding localization message bundles with keycloak config-cli. 

Only issue I faced is, I could not get the `18.0.2` build running. Mostly because I had to introduce a `legacy` file already for kc pre 22. And then below version 20, the behavior changed again. But as keycloak-config-cli claims to support only the latest for keycloak releases, it might make sure to drop the support for versions below 20 anyway...

**Comment by st3v0rr** [comment]
Hello @antikalk ,
if we apply this change we would break with the Red Hat SSO compatibility.
So for now I need some more feedback of potential Red Hat SSO users.
I think the reason @thomasdarimont wanted to keep it was because there are still projects that are dependent on this version.

There is also no new announcement from Red Hat on their new Keycloak product that would help us with the other pinned issue. https://github.com/adorsys/keycloak-config-cli/issues/992

**Comment by antikalk** [comment]
@st3v0rr Thanks for your response! I did just have another look at my PR and found a way to enable support for KC18.
