### ISSUE TITLE
Compatibility with "RedHat Build of Keycloak"

### ISSUE THREAD

**Issue by malexmave** [adorsys/keycloak-config-cli#992]
### Problem Statement

In the docs, you state that you are not officially supporting RedHat SSO. Since RedHat SSO is going to go EOL soon, and will be replaced by "[RedHat Build of Keycloak](https://access.redhat.com/products/red-hat-build-of-keycloak)": Does your policy of "we don't officially support this setup" also apply to the new RedHat Build of Keycloak, or is it close enough to mainline OSS Keycloak that you will officially support it?

(For some companies, "no official support of this combination" means that your tool cannot be used, hence clarity here would be appreciated)

### Proposed Solution

Update the documentation to explicitly state whether RedHat Build of Keycloak is supported.

### Environment

Not relevant to the question :)

### Acceptance Criteria

- [ ] Documentation states whether RedHat Build of Keycloak is supported or not

**Comment by st3v0rr** [comment]
Hello everyone,
we wanted to check first if there is a possibility to support it.
In the meantime I will Pin this issue.

**Comment by Motouom** [comment]
Hello @malexmave.

There is no way for us to test it with RedHat as we do no have the licence, so we don't support RedHat SSO.
In general, RedHat SSO version will be always mapped to a keycloak version, so you can use it as a hint to know if a dedicated RedHat SSO can work. Also, you could give us access to your RedHat SSO license.
